### ISSUE TITLE
new module: AMPlify

### ISSUE THREAD

**Issue by jasmezz** [nf-core/modules#1072]
I think it would be good to have a module for [AMPlify](https://bioconda.github.io/recipes/amplify/README.html)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by muffato** [comment]
@jasmezz  @Darcy220606 : is https://github.com/nf-core/modules/tree/master/modules/nf-core/amplify/predict enough ?

**Comment by jasmezz** [comment]
Oh this issue was forgotten to be closed! Yes, amplify predict is fine for now. If we need the `train` module in the future, we might add it then.
