### ISSUE TITLE
[FEATURE] Change `suffix` to allow complete freedom

### ISSUE THREAD

**Issue by jfy133** [nf-core/modules#1102]
## Is your feature request related to a problem? Please describe

With the new nf-core DSL2 v2.0 module syntax, defining output filenames with `suffix` are now embedded in a `process` block. The nice thing about this, is that this variable is now evaluated in the process itself, so can pick up variables with the process to define the name.

However, currently, if a`suffix` is supplied, the `${meta.id}` is hardcoded into the 'custom' output file name.

## Describe the solution you'd like

Drop `${meta.id}` from the condition where a `suffix` is supplied, therefore leaving `suffix` entirely up to the pipeline developer (i.e., whatever is specified in `modules.conf`). 

## Additional context
https://nfcore.slack.com/archives/CJRH30T6V/p1638182324466300)

**Comment by mahesh-panchal** [comment]
This is done now, no?

**Comment by jfy133** [comment]
Yes done! Finally completed in: https://github.com/nf-core/modules/pull/1117
