### ISSUE TITLE
[FEATURE] Filename collision when concatenating fastq with the same filename

### ISSUE THREAD

**Issue by jinmingda** [nf-core/modules#1104]
## Is your feature request related to a problem? Please describe

An error was raised when I try to concatenate fastq files with the same filename. The fastq files have the same name but come from different sequencing runs and are stored in separate locations. For example, `s3://mybucket/run_1/sample.fastq.gz` , `s3://mybucket/run_2/sample.fastq.gz`

## Describe the solution you'd like

I was wondering if we could avoid filename collision by simply staging the fastq files to concatenate in different subfolders in the task work directory.

We can change the following line of code

https://github.com/nf-core/modules/blob/1f8f86b79361fb9999b56680105f439df81d718d/modules/cat/fastq/main.nf#L11

to

```nextflow
tuple val(meta), path(reads, stageAs: "input*/*")
```

**Comment by drpatelh** [comment]
If that works and is a tested solution then that would be awesome @jinmingda ! We would be able to close this too 🎉 https://github.com/nf-core/rnaseq/issues/664

**Comment by drpatelh** [comment]
Fancy creating a PR?

**Comment by jinmingda** [comment]
@drpatelh I'd be glad to. Let me work on the PR.
