### ISSUE TITLE
new module: Metawrap

### ISSUE THREAD

**Issue by maxibor** [nf-core/modules#1123]
I think it would be good to have modules for [metaWRAP](https://github.com/bxlab/metaWRAP)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by ramprasadn** [comment]
Hi there!

We’ve noticed there hasn’t been much activity here. Are you still planning on working on this?
If not, you can ignore this message and we’ll close your PR/Issue in about 2 weeks or add it to the hackathon board 2023.

Cheers
the nf-core maintainers
