### ISSUE TITLE
[FEATURE] Update seqwish/induce to require compressed GFA and PAF files

### ISSUE THREAD

**Issue by heuermh** [nf-core/modules#1145]
Per e.g. https://github.com/nf-core/modules/issues/671, `seqwish/induce` should be updated to require compressed GFA and PAF formatted files.

**Comment by heuermh** [comment]
Ping @subwaystation for comment

**Comment by heuermh** [comment]
https://github.com/nf-core/pangenome/issues/70

**Comment by subwaystation** [comment]
So the idea is to use e.g. `pigz` to compress a GFA before we plug that into `seqwish`?
That would mean for each process in a pipeline we would have to compress and decompress each time?

**Comment by heuermh** [comment]
It's a trade off between CPU usage within a process and I/O overhead and storage costs inbetween processes (which could be hitting the network, e.g. writing to s3).  Perhaps best to implement without compression first and then run some benchmarks to compare.

It appears `wfmash` would prefer its inputs compressed using block-compressed GZIP (BGZF) and indexed
https://github.com/ekg/wfmash#input-indexing

Might be worth using BGZF instead of GZIP across the board as it can be more easily split for parallel/distributed algorithms.

**Comment by subwaystation** [comment]
I think the `wfmash` version currently on Bioconda does not support BGZF zipped files, yet, I think. Pinging @AndreaGuarracino .

**Comment by AndreaGuarracino** [comment]
`wfmash` on Bioconda already supports BGZF zipped files, but it will not complain if it is not indexed. Instead, new versions will require an index for the input FASTA file for the target sequences for scalability reasons (when your input FASTA is 300GB, the next `wfmash` version will be much more memory polite than the current 0.7.0). As soon as we confirm that the new `seqwish` version on bioconda works correctly in nf-core/modules, I will continue and update` wfmash`'s bioconda recipe as well.

I agree to compress stuff. `seqwish` would already be happy to accept compressed PAF files as input. Actually, I always compress them (and other files too) with large datasets to avoid being warned of "out of space "on the clusters.

**Comment by heuermh** [comment]
Fixed by #2083
