### ISSUE TITLE
new module: samtools/markdup

### ISSUE THREAD

**Issue by priyanka-surana** [nf-core/modules#1231]
I think it would be good to have a module for [markdup](https://www.htslib.org/doc/samtools-markdup.html)

- This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by muffato** [comment]
Closed by #2087
