### ISSUE TITLE
Kraken2 is a single tool and process name needs to reflect that

### ISSUE THREAD

**Issue by sateeshperi** [nf-core/modules#1381]
[kraken2](https://github.com/nf-core/modules/blob/master/modules/kraken2/kraken2/main.nf) module is a single tool but has been named as `process KRAKEN2_KRAKEN2` leading to a false interpretation that it has sub-tools.

[Related PR](https://github.com/nf-core/modules/blob/master/modules/kraken2/kraken2/main.nf)

**Comment by MillironX** [comment]
Was this so that there could also be a `KRAKEN2_BUILD` module, though?

**Comment by drpatelh** [comment]
> Was this so that there could also be a KRAKEN2_BUILD module, though?

Yes, exactly. We are trying to standardise our naming conventions and this was the most obvious solution given that you can run the tool as `kraken2` or `kraken2-build`.
