### ISSUE TITLE
Write custom test for checking contents of BAM file.

### ISSUE THREAD

**Issue by Emiller88** [nf-core/modules#141]
https://pytest-workflow.readthedocs.io/en/stable/#writing-custom-tests

Bowtie/2 include in the header the run commands, which are never going to be the same, so the md5 hash will never be equal across different containers. 
```
$ samtools view -H test.bam
## Singularity
@HD     VN:1.0  SO:unsorted
@SQ     SN:gi|170079663|ref|NC_010473.1|        LN:4686137
@PG     ID:bowtie2      PN:bowtie2      VN:2.4.2        CL:"/usr/local/bin/bowtie2-align-s --wrapper basic-0 -x ./bowtie2/NC_010473 --threads 1 -1 test_R1.fastq.gz -2 test_R2.fastq.gz"
@PG     ID:samtools     PN:samtools     PP:bowtie2      VN:1.11 CL:samtools view -@ 1 -bhS -o test.bam -
## Conda
@HD     VN:1.0  SO:unsorted
@SQ     SN:gi|170079663|ref|NC_010473.1|        LN:4686137
@PG     ID:bowtie2      PN:bowtie2      VN:2.4.2        CL:"/tmp/pytest_workflow_4fbqrxe4/Run_bowtie2_index_and_align_paired-end/work/conda/env-10b78180015f409ae983f51f20f43c6a/bin/bowtie2-align-s --wrapper basic-0 -x ./bowtie2/NC_010473 --threads 1 -1 test_R1.fastq.gz -2 test_R2.fastq.gz"
@PG     ID:samtools     PN:samtools     PP:bowtie2      VN:1.11 CL:samtools view -@ 1 -bhS -o test.bam -
```

**Comment by drpatelh** [comment]
I think we can get away by importing the `SAMTOOLS_FLAGSTAT` in every module that generates a BAM file and checking the `md5sum` of that. If the `SAMTOOLS_FLAGSTAT` process fails then it will almost certainly indicate that the BAM file is corrupted.

**Comment by Emiller88** [comment]
I was thinking we essentially run the same thing `SAMTOOLS_FLAGSTAT` is doing but in pytest-workflow, possibly even with [pysam](https://pysam.readthedocs.io/en/latest/api.html) but I don't want to add another outside dependancy for testing. Plus I think the nextflow will be easier for everyone to wrangle, rather than making understanding the tests a barrier for entry.

**Comment by drpatelh** [comment]
Not sure what we can do here without adding other dependencies / chains of modules to the tests which in itself isn't ideal given that the size of the repo and tests will only grow. I suggest we leave things as they are for now and see if we can come up with a cleverer solution in the future.
