### ISSUE TITLE
Adding new modules link does not work

### ISSUE THREAD

**Issue by jpfeuffer** [nf-core/modules#1430]
Sorry for being brief. On the phone.

## Check Documentation

I have checked the following places for your error:

- [ ] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [ ] [nf-core/module documentation](https://github.com/nf-core/modules/blob/master/README.md)

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: 
2. See error: 

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the module
- [ ] The `.nextflow.log` file 

## System

- Hardware: 
- Executor: 
- OS: 
- Version 

## Nextflow Installation

- Version: 

## Container engine

- Engine: 
- version: 
- Image tag:

**Comment by Emiller88** [comment]
@jpfeuffer I moved it to https://nf-co.re/developers/modules in https://github.com/nf-core/nf-co.re/pull/1090 and https://nf-co.re/developers/tutorials/dsl2_modules_tutorial if someone is looking for an intro to creating modules.

Let me know where you saw a broken link, or feel free to PR it yourself!

**Comment by jpfeuffer** [comment]
Ah sorry forgot to mention that. see PR
