### ISSUE TITLE
[BUG] controlfreec fails with conda

### ISSUE THREAD

**Issue by Emiller88** [nf-core/modules#1455]
Follow up to

https://github.com/nf-core/modules/pull/1452#discussion_r835546725

In the conda tests
```
cat: /usr/local/bin/assess_significance.R: No such file or directory
mv: cannot stat '*.p.value.txt': No such file or directory
```
We should figure out in assess_signifcance can just be called.

**Comment by FriederikeHanssen** [comment]
See #1504
