### ISSUE TITLE
Use --seed parameters for aligners / other tools wherever possible

### ISSUE THREAD

**Issue by drpatelh** [nf-core/modules#147]
Given that we are now testing for the same outputs generated by a given module in order to detect changes as a result of updating the module itself, it would be good if we can somehow factor in instances where for example alignments are generated at random if the same tool is run more than once. This will rightly break the CI tests but one way around that is to use `--seed` parameters if available e.g. [Bowtie2](http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#bowtie2-options-seed).

The implementation should be as simple as passing the appropriate optional argument to the tool in the `main.nf` script for the tests.

Also see https://github.com/nf-core/modules/pull/143#discussion_r570147386

**Comment by ramprasadn** [comment]
Hi there!

We’ve noticed there hasn’t been much activity here. Are you still planning on working on this?
If not, you can ignore this message and we’ll close your issue in about 2 weeks

Cheers
the nf-core maintainers
