### ISSUE TITLE
RFC: New subworkflow bam_qc

### ISSUE THREAD

**Issue by matthdsm** [nf-core/modules#1516]
Hi,

I'd like to suggest a new submodule containing common QC steps performed on BAM data. The input would be a single bam (+index) and spit out ready to use QC reports. Additions or replacements of suggested tools are welcome.

```mermaid
flowchart LR
    QC_BAM([BAM])           --> SAMTOOLS_STATS[Samtools stats]
    QC_BAM([BAM])           --> SAMTOOLS_IDXSTATS[Samtools idxstats]
    QC_BAM([BAM])           --> USE_PICARD{use Picard?}
    USE_PICARD              --> COLLECTMULTIPLEMETRICS[Picard CollectMultipleMetrics]
    USE_PICARD              --> TARGETTED{Targetted?}
    TARGETTED               --YES--> COLLECTHSMETRICS[Picard CollectHSMetrics]
    TARGETTED               --NO-->  COLLECTWGSMETRICS[Picard CollectWGSMetrics] 
```
- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by maxulysse** [comment]
I like the idea, I think we have something similar in sarek, but maybe split in separate subworkflows (or maybe organized differently due to CRAM input), don't hesitate to ping me whenever
