### ISSUE TITLE
new module: DIAMOND/BLASTX

### ISSUE THREAD

**Issue by jfy133** [nf-core/modules#1529]
I think it would be good to have a module for [DIAMOND](https://bioconda.github.io/recipes/diamond/README.html)

- [ ] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [ ] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [ ] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by rpetit3** [comment]
I think we might be good: https://github.com/nf-core/modules/tree/master/modules/diamond

Looks like just `prepdb` is missing

**Comment by jfy133** [comment]
Whoops, GitHub search failed me there.

PrepDB not necessary for taxprofiler so we can Ignore that for now I guess
