### ISSUE TITLE
[BUG]  ps binary missing from nfcore/bclconvert:3.9.3

### ISSUE THREAD

**Issue by MrMarkW** [nf-core/modules#1563]
## Check Documentation

I have checked the following places for your error:

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core/module documentation](https://github.com/nf-core/modules/blob/master/README.md)

## Description of the bug

`ps` binary missing from `nfcore/bclconvert:3.9.3`

## Steps to reproduce

Steps to reproduce the behaviour:

1. run bclconvert module in pipeline on Tower
2. See error: `Command 'ps' required by nextflow to collect task metrics cannot be found`

## Expected behaviour

Not to throw error with Tower plugin

## Log files

```
[91/fa31a3] Submitted process > BLC_CONVERT:BCLCONVERT ($samplesheet)
Error executing process > 'BLC_CONVERT:BCLCONVERT ($samplesheet)'
Caused by:
  Essential container in task exited
Command executed:
  bcl-convert \
       --force \
      --output-directory . \
      --bcl-input-directory MYDIR \
      --sample-sheet SampleSheet.csv \
      --bcl-num-parallel-tiles 32
 ...

Command exit status:
  1
Command output:
  (empty)
Command error:
  nxf-scratch-dir ...:/tmp/nxf.LEutuEnMzX
  Command 'ps' required by nextflow to collect task metrics cannot be found
```

## System

- Hardware: CLOUD
- Executor: AWS-BATCH
- OS: Linux

## Nextflow Installation

- Version: 21.10.6 build 5660

## Container engine

- Engine: Docker
- version: latest
- Image tag: nfcore/bclconvert:3.9.3

## Additional context

To make this work, I created own version of the bclconvert image.  I believe the image just needs to be rebuilt and pushed.  

I also have an issue where it requires me to set `--force ` because it says there is existing data in `--output-directory .`

**Comment by Emiller88** [comment]
It's fixed now by https://github.com/nf-core/demultiplex/issues/30
