### ISSUE TITLE
Get rid of the DSL2 nextflow declaration in tests main.nf

### ISSUE THREAD

**Issue by JoseEspinosa** [nf-core/modules#1577]
From Nextflow version `22.4.0`, the DSL2 declaration is not needed anymore at the top of the script (i.e. `nextflow.enable.dsl = 2`). See [here](https://www.nextflow.io/blog/2022/evolution-of-nextflow-runtime.html). Hence, it can be removed from all the tests `main.nf` scripts.

**Comment by SPPearce** [comment]
This is not present in the nf-test tests, so slowly being dropped anyway, so closing the issue now.
