### ISSUE TITLE
Samtools bam2fq doesn't seem to produce gziped output when `split == false`

### ISSUE THREAD

**Issue by ljmesi** [nf-core/modules#1598]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

When `split == false`, samtools bam2fq doesn't produce gziped fastq files as output as is expected. 

### Command used and terminal output

When I ran the module and then later inspected the output file with: `file ERR3201952_ERR3201952_interleaved.fq.gz`. I received following output:
`ERR3201952_ERR3201952_interleaved.fq.gz: ASCII text, with very long lines`.

However when I added to the command the `gzip` command:

```shell
samtools \\
  bam2fq \\
  $args \\
  -@ $task.cpus \\
  $inputbam | gzip > ${prefix}_interleaved.fq.gz
```

and ran the same `file` command, I received: `ERR3201952_ERR3201952_interleaved.fq.gz: gzip compressed data, from Unix, original size modulo 2^32 27948851` as output.

**Comment by mahesh-panchal** [comment]
Is it because `false` is a string?
The solution is then to change https://github.com/nf-core/modules/blob/6bb9be38c5790c70d9b3fe56957a2f33f2b43758/modules/samtools/bam2fq/main.nf#L25
to 
```
split.toBoolean()
```

**Comment by ljmesi** [comment]
No, it seemed that with the `split == false` side of logic, `samtools bam2fq` doesn't automatically compress the output fastq file as it does with `split == true` side so the solution was to add compression tool in the middle between the `samtools bam2fq` output and the redirection. Here is a link to the [PR](https://github.com/nf-core/modules/pull/1606).

**Comment by mahesh-panchal** [comment]
Ah, ok. So I guess it's safe to close this issue then.

**Comment by ljmesi** [comment]
Yes, I think so too. I can close it.
