### ISSUE TITLE
new module: GAMMA-S

### ISSUE THREAD

**Issue by MzDiaz824** [nf-core/modules#1664]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by famosab** [comment]
This is closed by PR #1532 and a duplicate of #1531
