### ISSUE TITLE
new module: ffq

### ISSUE THREAD

**Issue by Emiller88** [nf-core/modules#1684]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by Emiller88** [comment]
https://github.com/pachterlab/ffq

**Comment by jfy133** [comment]
https://github.com/nf-core/modules/pull/1842
