### ISSUE TITLE
new module: trimmomatic

### ISSUE THREAD

**Issue by alyssa-ab** [nf-core/modules#1720]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by alyssa-ab** [comment]
Creating module for [trimmomatic](http://www.usadellab.org/cms/?page=trimmomatic)
Using [cutadapt](https://github.com/nf-core/modules/blob/7a83ca30704e002bc4ba79d892ba364592c6db7f/modules/cutadapt/main.nf) as a reference module for a similar process.

**Comment by alyssa-ab** [comment]
[Script main.nf](https://github.com/alyssa-ab/modules/blob/trimmomatic/modules/trimmomatic/main.nf)
[Test main.nf](https://github.com/alyssa-ab/modules/blob/trimmomatic/tests/modules/trimmomatic/main.nf)

**Comment by alyssa-ab** [comment]
Test fails [Command exit status: 1]

.command.err output
`Command error:                                                                              
           Usage:                                                                                    
                  PE [-version] [-threads <threads>] [-phred33|-phred64] [-trimlog                   
         <trimLogFile>] [-summary <statsSummaryFile>] [-quiet] [-validatePairs]                      
         [-basein <inputBase> | <inputFile1> <inputFile2>] [-baseout <outputBase> |                  
         <outputFile1P> <outputFile1U> <outputFile2P> <outputFile2U>] <trimmer1>...                  
              or:                                                                                    
                  SE [-version] [-threads <threads>] [-phred33|-phred64] [-trimlog                   
         <trimLogFile>] [-summary <statsSummaryFile>] [-quiet] <inputFile>                           
         <outputFile> <trimmer1>...                                                                  
              or:                                                                                    
                  -version                          `

.command.sh
`#!/bin/bash -ue
trimmomatic \
    --cores 2 \
     \
    -o test.trim.fastq.gz \
    test_1.fastq.gz \
    > test.trimmomatic.log
cat <<-END_VERSIONS > versions.yml
"test_trimmomatic_single_end:TRIMMOMATIC":
    trimmomatic: $(trimmomatic --version)
END_VERSIONS`

**Comment by Emiller88** [comment]
Ah, the issue is that trimmomatic handles the PE and SE differently than cutadapt:
```nextflow
def trimmed  = meta.single_end ? "SE ${prefix}.trim.fastq.gz" : "PE ${prefix}_1.trim.fastq.gz ${prefix}_2.trim.fastq.gz"
```
Or actually
```
def trimmed  = meta.single_end ? "SE ${reads}" : "PE ${reads}"
```
might work.
