### ISSUE TITLE
new module: polyastripper

### ISSUE THREAD

**Issue by alyssa-ab** [nf-core/modules#1759]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by Emiller88** [comment]
JK, it's a custom script https://github.com/broadinstitute/CTAT-VirusIntegrationFinder/blob/52181c51d634128a84a774838a61c1bae0acbf23/util/fastq_polyA_stripper.py
