### ISSUE TITLE
new module: entrezdirect/esearch

### ISSUE THREAD

**Issue by alxndrdiaz** [nf-core/modules#1771]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by alxndrdiaz** [comment]
I am working on the `entrezdirect/esearch `module for the [blobtoolkit pipeline](https://github.com/sanger-tol/blobtoolkit).

**Comment by MillironX** [comment]
Related:

- https://github.com/BioContainers/containers/issues/441
- https://github.com/bioconda/bioconda-recipes/pull/35235
- https://github.com/ksumngs/nf-modules/pull/1

**Comment by alxndrdiaz** [comment]
Latest entrez-direct (16.2-1) Docker container version still has a bug: 

```
entrezdirect_img_latest='quay.io/biocontainers/entrez-direct:16.2--he881be0_1'
database="pubmed"
term="Hox-genes"

docker run \
--rm \
-v $(pwd):$(pwd) \
-w $(pwd) \
-t ${entrezdirect_img_previous} \
esearch -db ${database} -query ${term}
```

```
Can't locate Time/HiRes.pm in @INC (you may need to install the Time::HiRes module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base).
BEGIN failed--compilation aborted.

<ENTREZ_DIRECT>
  <Db>pubmed</Db>
  <WebEnv>MCID_62ac9c50d7198b20634e5a32</WebEnv>
  <QueryKey>1</QueryKey>
  <Count>17387</Count>
  <Step>1</Step>
</ENTREZ_DIRECT>
```

For development a previous working version (13.9-0) will be used.
