### ISSUE TITLE
new module: ascat

### ISSUE THREAD

**Issue by maxulysse** [nf-core/modules#186]
I think it would be good to have a module for [ascat](https://bioconda.github.io/recipes/ascat/README.html)

**Comment by lassefolkersen** [comment]
[Maria](https://github.com/aasNGC) and I are looking into this.

**Comment by lassefolkersen** [comment]
We have a [very very early draft](https://github.com/aasNGC/modules), but one issue that comes up is that it's not really ready for sequencing data
> We are working on an integrated and automated whole genome, exome and targeted sequencing version that runs directly from BAM files.

> ASCAT input files can also be derived from massively parallel sequencing data, through log-transformed normalised read depth (LogR) and allele frequencies (BAF) of selected SNP loci.

Is what it currently [says](https://www.crick.ac.uk/research/labs/peter-van-loo/software). So it requires quite a lot of extra work up front to make it start from BAM files.

I've written the lab and ask if there's any updates I've missed.

**Comment by lassefolkersen** [comment]
Great news @aasNGC I talked to the vanLoo-lab people and they are releasing the [3.0 ASCAT](https://github.com/VanLoo-lab/ascat/pull/83) version right now, and that does take bam input. I'll get it through with bioconda and such, and then we can proceed.

**Comment by lassefolkersen** [comment]
The [v3.0.0 ](https://github.com/VanLoo-lab/ascat/releases/tag/v3.0.0)is now released. I've just [put in a version-bump ](https://github.com/bioconda/bioconda-recipes/pull/32817)pull request at bioconda, so should be available as dockers and singularities from there soon. Once it is I'll go back to that [old fork](https://github.com/aasNGC/modules) from @assNGC and finish up the module.
