### ISSUE TITLE
Port modules and single-tool workflows from Babraham

### ISSUE THREAD

**Issue by FelixKrueger** [nf-core/modules#19]
I'll be working on adding the modules and single-tool workflows that were already used and tested at the Babraham.

To avoid duplication of efforts, the tools I'll be working on initially will include the following:

**QC**
- [x] FastQC
- [x] FastQ Screen
- [x] MultiQC

**Trimming**
- [x] Trim Galore

**Alignment**
- [x] Bowtie2
- [x] HISAT2
- [x] Bismark
- [x] deduplicate_bismark
- [x] bismark_methylation_extractor
- [ ] bismark2bedGraph
- [x] coverage2cytosine
- [x] bismark2summary
- [x] bismark2report

**Read Simulator:**
- [ ] Sherman

**Allele-specific sorting:**
- [ ] SNPsplit

**Comment by apeltzer** [comment]
Adding Modules: super cool - workflows/single tool workflows - not sure how we will shape that in here in the repository. 

Maybe I missed some discussion on this @nf-core/core someone knows how we intend this to go forward in the future / discussed this maybe already? :-)

**Comment by FelixKrueger** [comment]
We have talked about it briefly, but I think the format is still a little bit up in the air. The sentiment seems to have been been that *any* form of content is probably better than nothing, and one can then still get everything into a more unified structure a little later.

I am currently in the process of changing all current modules and workflows we have at the Babraham, to incorporate the recent changes in Nextflow mentioned by Paolo yesterday (e.g. passing on of parameters, or the impending deprecation of `publish:` within workflows). Once I am happy that they do work in principle I'll confer with Phil again (hopefully by tomorrow morning), and will then try to bring start doing pull requests in a format that we can agree on. Does that sound like a plan?

**Comment by apeltzer** [comment]
Sounds cool to me :-) Also think that adding anything is better than having almost nothing in here, so why not ;-)

**Comment by naepfel** [comment]
I'd be glad to learn about our strategy here as well. Have there been any discussions on potential unified structures? Should all workflows consist of modules in the future? Whould we have a repository for both modules and workflows? I am currently having these discussions quite bit here with local people

**Comment by apeltzer** [comment]
I guess its not really settled yet - `modules` would be for single tool encapsulation, workflow could then be a concatenation of multiple modules that do a certain purpose - whereas what we call pipeline/workflows at the moment would then be a combination of atomic modules and/or multiple such smaller workflows.

The structure how the modules should look like in here (metadata etc pp) is currently evaluated I think - also how we install these see #8 for more info on this. Its not that easy to say which way forward is the best for this I think.

**Comment by grst** [comment]
we should have most of those modules in now. Can this be closed?

**Comment by louperelo** [comment]
Hi there!

We’ve noticed that most of the proposed modules have been created and merged. Are you still planning on working on the rest of the tools on the list (bismark2bedGraph, Sherman, SNPsplit)? 
If not, you can ignore this message and we’ll close your issue in about 2 weeks


Cheers
the nf-core maintainers
