### ISSUE TITLE
new module: wget

### ISSUE THREAD

**Issue by muffato** [nf-core/modules#1920]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by robsyme** [comment]
Hi Matthieu

What are the features you'd want in a `wget` module that are not already available using the `Channel.fromPath` and `file(your_url)` features available in vanilla Nextflow?

**Comment by Emiller88** [comment]
https://github.com/nextflow-io/nextflow/issues/1873

**Comment by muffato** [comment]
I think all the cases a nf-core wget module would need to cover are already in Nextflow, indeed. It doesn't suit every pipeline, but the solutions are pipeline-specific and don't fit nf-core either. Happy to leave this ticket closed.
