### ISSUE TITLE
new module: Imputation (Glimpse, Beagle, Impute, Shapeit)

### ISSUE THREAD

**Issue by LouisLeNezet** [nf-core/modules#1974]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by LouisLeNezet** [comment]
I'm going to write an imputation pipeline using the nf-core templates and recommendations.
I think it would be nice to have all the different software available as modules in nf-core (Glimpse, Shapeit, Beagle, Impute).
Could it be possible ?
I already started writing the different modules for Glimpse.

Thanks

**Comment by famosab** [comment]
Is this solved with #2857?

**Comment by LouisLeNezet** [comment]
I think this can effectively be closed.
Thanks for the reminder.
