### ISSUE TITLE
Module file versioning

### ISSUE THREAD

**Issue by drpatelh** [nf-core/modules#2]
We need to come up with a way to version each module or at least be able to use a particular version of a module within the main pipeline script. Through previous discussions we have somewhat agreed that we need to be able to do this via git commit as we are able to do with `nf-core/configs`. Whether we are able to do this at the level of individual module files or a commit id for the entire `nf-core/modules` repo is still up for discussion.

**Comment by ewels** [comment]
See https://github.com/nf-core/modules/issues/8 for an idea on how to handle this in pipelines. That approach enforces an answer for this issue.

**Comment by junjun-zhang** [comment]
@drpatelh we are experimenting a solution to do just that, ie, versioning individual modules. Here is one of our modules/tools: [bwa-mem-aligner.nf](https://github.com/icgc-argo/dna-seq-processing-tools/blob/master/tools/bwa-mem-aligner/bwa-mem-aligner.nf). Note that each module/tool is completely self-sufficient and accompanied with its own docker image. Although the github repo includes many modules/tools, we release each of them independently, eg, [bwa-mem-aligner.0.1.3.0](https://github.com/icgc-argo/dna-seq-processing-tools/releases/tag/bwa-mem-aligner.0.1.3.0). This may seem controversial, but it has been practised by GO language, see [sdk/v0.3.0](https://github.com/hashicorp/consul/releases/tag/sdk%2Fv0.3.0), [api/v1.30](https://github.com/hashicorp/consul/releases/tag/api%2Fv1.3.0) and [v1.6.2](https://github.com/hashicorp/consul/releases/tag/v1.6.2), all of them are from the same GitHub repo: [hashicorp/consul](https://github.com/hashicorp/consul).

In terms importing specific version of the module files into pipeline code, we first make hard copies of these files in the github repo of the pipeline code, eg, under [here](https://github.com/icgc-argo/dna-seq-processing-wfs/tree/e35b822b43b5abcc6b3454f6cb29f78f3dd8858a/modules/), then include them into the pipeline code like [this](https://github.com/icgc-argo/dna-seq-processing-wfs/blob/e35b822b43b5abcc6b3454f6cb29f78f3dd8858a/dna-seq-alignment/main.nf#L56-L58).

This is more of an attempt from us, but it works well for our needs so far. Se ongoing discussion regarding the importing mechanism in #8 as @ewels pointed out. We'd love to hear thoughts from other community members.

**Comment by drpatelh** [comment]
See https://github.com/nf-core/modules/issues/2#issuecomment-562061173
