### ISSUE TITLE
Decide on proper naming convention for subworkflows

### ISSUE THREAD

**Issue by maxulysse** [nf-core/modules#2157]

**Comment by scorreard** [comment]
Here are some notes from the team brainstorming

**Naming convention :** 
_<input_filetype>_<operation>_<ToolNames>_
Ex : bam_sort_samtools
Everything is in lowercase

**Input filetype**
File type of the initial input file
Ex : fastq, bam, vcf, etc

**Operation**
The operation should describe as best as possible the sub-workflow task.
An ontology will be done to make sure we use the same operation name.
Ex : align for alignment or mapping

**Tool name**
Include the names of all the tools that are used in the subworkflow
If several tools are used in the subworkflow, the tool name(s) should be ordered as used in the subworkflow and separated by underscores.
If the tool is used several times in the subworkflow, the tool name should be included only once in the naming of the subworrkflow. 
If the tool includes options, do not include the option name (i.e. if I use ‘samtools index’ and ‘samtools sort’, I only include ‘samtools’ once in the subworkflow name)

**Comment by scorreard** [comment]
Should the input file name be limited to only one file format?
For now, yes.

For example :  
bam_somatic_variant_calling_gatk
or
bam_cram_somatic_variant_calling_gatk
