### ISSUE TITLE
fix tests: bcftools_filter and bcftools_stats

### ISSUE THREAD

**Issue by MaxUlysse** [nf-core/modules#216]
Given the errors for `bcftools` (file not existing, I'm assuming it's an issue with singularity):
- https://github.com/nf-core/modules/runs/1914822936
- https://github.com/nf-core/modules/runs/1914823041

**Comment by JoseEspinosa** [comment]
I checked the `log` from the tests and seems it was a temporal problem when downloading the image, I copied the error message below:

```
Caused by:
  Failed to pull singularity image
  command: singularity pull  --name depot.galaxyproject.org-singularity-bcftools-1.11--h7c999a4_0.img.pulling.1613520160414 https://depot.galaxyproject.org/singularity/bcftools:1.11--h7c999a4_0 > /dev/null
  status : 255
  message:
    FATAL:   Error making http request: Head "https://depot.galaxyproject.org/singularity/bcftools:1.11--h7c999a4_0": dial tcp 128.118.250.14:443: i/o timeout
```
    
I run the test locally with `singularity` and they worked as expected we may want to relaunch the tests and confirm it.

**Comment by JoseEspinosa** [comment]
I just updated my fork and both `bcftools filter` [here](https://github.com/JoseEspinosa/modules/runs/1918710944?check_suite_focus=true) `bcftools stats` [here](https://github.com/JoseEspinosa/modules/runs/1918711133?check_suite_focus=true) worked. So I'd say we can close the issue
