### ISSUE TITLE
new module: orthofinder/orthofinder

### ISSUE THREAD

**Issue by baptisteImbert** [nf-core/modules#2196]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by bagrezildo** [comment]
I'm taking this over

**Comment by GallVp** [comment]
Hi @bagrezildo 

I am also working on it. If you have made any progress, let's share it. Thank you!
