### ISSUE TITLE
[Documentation]: Add mermaid diagram requirement to subworkflow docs

### ISSUE THREAD

**Issue by matthdsm** [nf-core/modules#2218]
Add a requirement for a (mermaid) diagram to subworkflow docs. This diagram should be added to a readme doc inside the subworkflow dir.

**Comment by Emiller88** [comment]
I think we should use the class diagram https://mermaid-js.github.io/mermaid/#/classDiagram

**Comment by Emiller88** [comment]
Going to have to manually add the `README.md` file for now.

https://github.com/nf-core/modules/pull/2217#issuecomment-1274560734 we should add the README creation with a mermaid template to `nf-core subworkflow create`

**Comment by Emiller88** [comment]
> This would be nice. We just need to make sure we lint to check that the mermaid diagram has always been generated relative to the latest version of the subworkflow.
- @drpatelh

**Comment by Emiller88** [comment]
```mermaid
graph TD
    A(HOMER_MAKETAGDIRECTORY) -->|tagdir| B(HOMER_MAKEUCSCFILE)
    A -->|tagdir| C(HOMER_FINDPEAKS)
    C -->|txt| D(HOMER_POS2BED)

    subgraph ide1 [emit]
        A -->|tagdir| t(tagdir)
        B -->|bedGraph| b(bed_graph)
        C -->|txt| p(peaks)
        D -->|bed| e(bed)
        end
  ```

**Comment by matthdsm** [comment]
Somewhat more simple diagram
```mermaid
flowchart TD

ch_reads & ch_aligner_index & aligner --> alignerbowtie2{aligner == bowtie2}--> BOWTIE2_ALIGN
ch_reads & ch_aligner_index & aligner--> alignerbwamem{aligner == bwamem} --> BWAMEM_MEM
ch_reads & ch_aligner_index & aligner --> alignerbwamem2{aligner == bwamem2}--> BWAMEM2_MEM
ch_reads & ch_aligner_index & aligner --> alignerdragmap{aligner == dragmap}--> DRAGMAP_ALIGN
ch_reads & ch_aligner_index & aligner --> alignersnap{aligner == snap}--> SNAPALIGNER_ALIGN

BOWTIE2_ALIGN & BWAMEM_MEM & BWAMEM2_MEM & DRAGMAP_ALIGN & SNAPALIGNER_ALIGN ----> bam & bai & reports & versions

```

**Comment by mashehu** [comment]
talked shortly about it in the last maintainers-meeting, but no strong support for this.
