### ISSUE TITLE
Node.js 12 actions are deprecated.

### ISSUE THREAD

**Issue by lucacozzuto** [nf-core/modules#2238]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

Hi, when doing tests I got this warning:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, dorny/paths-filter, actions/checkout
```

Not so sure is a problem right now or it will be in the close future

**Comment by Emiller88** [comment]
https://github.com/dorny/paths-filter/issues/156

**Comment by klkeys** [comment]
looks like @Emiller88 resolved this, closing for now
