### ISSUE TITLE
nf-core modules install is asking for two files

### ISSUE THREAD

**Issue by lucacozzuto** [nf-core/modules#2272]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

nf-core modules install is asking for two files: main.nf and nextflow.config. I think this is not necessary, since one can use a different naming convention for both files.

### Command used and terminal output

```console
nf-core modules install fastqc

WARNING  Can't find a '.nf-core.yml' file that defines 'repository_type'                                                                                                   module_utils.py:158
? Is this repository an nf-core pipeline or a fork of nf-core/modules? Pipeline
INFO     To avoid this prompt in the future, add the 'repository_type' key to a root '.nf-core.yml' file.                                                                  module_utils.py:169
? Would you like me to add this config now? [y/n] (y): y
INFO     Config added to '.nf-core.yml'                                                                                                                                    module_utils.py:173
ERROR    Could not find a 'main.nf' or 'nextflow.config' file in '.'
```

**Comment by awgymer** [comment]
I think this should be an issue in `nf-core/tools` but what is the reasoning to disable the checks?

**Comment by lucacozzuto** [comment]
Because is not mandatory to have a main.nf or nextflow.config file ina pipeline

**Comment by awgymer** [comment]
`nextflow.config` is mandatory in `nf-core` in the sense that pipeline linting will fail if it's not present. 
No `main.nf` is currently only a warning, but it's the default name for the file expected to be found by nextflow (you need to specify any alternative in the `nextflow.config` so although it's *technically* possible to have a pipeline without one I am not aware that any such case exists.

**Comment by lucacozzuto** [comment]
Agree.
