### ISSUE TITLE
CI overload when updating modules attached to subworkflows

### ISSUE THREAD

**Issue by matthdsm** [nf-core/modules#2295]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

Not really a bug per se, but here goes.

When updating a module attached to a subworkflow, the CI for that specific module keeps failing, as long as the workflow upstream isn't fixed.
This causes a lot of confusion IMO, especially when updating popular modules attached to many workflows.

Is there a way split this so we have a clear, separate ci run for the module and each attached workflow? That way, we can scratch of the issues one by one, instead of staring at a CI that keeps failing.

**Comment by Emiller88** [comment]
Yeah, it's a trade off. Configuring these with in the `pytest_software.yml` is brittle, and then there are two sources of truth for the relationships between modules and subworkflows. Splitting them might also bring in #391

I was thinking something like using Job Summaries (https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries) might make this a bit easier for people to pick out.

But for now I personally don't think it's the biggest priority, we may get to fix it for free with nf-test.
