### ISSUE TITLE
fgbio_create_umi_consensus: take aligner index instead of fasta

### ISSUE THREAD

**Issue by matthdsm** [nf-core/modules#2304]
### Is your feature request related to a problem? Please describe

The subworkflow shouldn't take a fasta file and create an aligner index - out of scope
xref #2302
xref #2179
xref #2185

### Describe the solution you'd like

Pregenerate the aligner index and use that as input. Doing this for each sample creates a huge amount of overhead

**Comment by lescai** [comment]
the indexing step is optional and conditional to passing an index when workflow is called:
```
take:
    reads                     // channel: [mandatory] [ val(meta), [ reads ] ]
    fasta                     // channel: [mandatory] /path/to/reference/fasta
    bwa_index                 // channel: [optional]  /path/to/reference/bwaindex
```
a condition has now been made explicit upon module call as well to fully address this.
