### ISSUE TITLE
new module: deepvariant

### ISSUE THREAD

**Issue by maxulysse** [nf-core/modules#234]
I think it would be good to have module for [deepvariant](https://bioconda.github.io/recipes/deepvariant/README.html)

**Comment by abhi18av** [comment]
Hi team,

I've started working on the development of the `deepvariant` module, however owing to the upcoming changes in the structure of `nf-core/modules`, I figured that it might be better to 

1. work on the [integration first as a `local` module](https://github.com/nf-core/sarek/pull/394) in `sarek` 
2. once the modules repo is stable again, I'll port over the sarek-specific local `deepvariant` code to a module.

**Comment by projectoriented** [comment]
Hello 👋!

How it's going? We're planning to use this module in our pipeline and was curious if there are any updates on this 😊 @ramprasadn

**Comment by abhi18av** [comment]
Hi @projectoriented ,

Actually, this module is a WIP as per nf-core/modules guidelines https://github.com/nf-core/modules/pull/572

I can prioritize the module this evening for you to hvae a look and circle back with feedback - would that be okay?

**Comment by projectoriented** [comment]
@abhi18av Thanks! I've added some comments, hope they help 😛
