### ISSUE TITLE
Migrate to nf-test meta tracking issue

### ISSUE THREAD

**Issue by Emiller88** [nf-core/modules#2341]
An issue to track the conversation about migrating to nf-test, and what we're waiting on because I keep losing track of the conversation.

```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/modules/pull/3228
```

**Comment by nvnieuwk** [comment]
PR with prototypes created during the hackathon: https://github.com/nf-core/modules/pull/2199

**Comment by nvnieuwk** [comment]
Awaited features are:
- `tags`
- `snapshots`

Issue on `nf-test` with `nf-core` suggestions: https://github.com/askimed/nf-test/issues/29

**Comment by aaron-fishman-achillestx** [comment]
HI @nvnieuwk  / @Emiller88 ,

Great to see community interest in nf-test. We are looking to migrate to it at my company as well - as we think it has great potential. Would be great to align and share efforts!

Planning to contribute features over the next two weeks with developers from my team so nf-test can [integrate better ](https://github.com/askimed/nf-test/issues/21)with our bitbucket CI workflows - and [compare maps](https://github.com/askimed/nf-test/issues/36).

**Comment by Emiller88** [comment]
So uh, I was working on https://github.com/nf-core/methylseq/issues/231, copying and pasting md5sums and running a vim macro on them, and I got fed up halfway through one file, and since it was only 12 tests or so, I thought "Let's use nf-test on this".

I set up the first test got it working, then I realized you can do `nf-test test` and it'll run all the tests. Thought that was cool.

Then, I thought, what if I pass it a wild card? :thinking: 
Would it run all the tests in a directory?

Sure enough, it worked!

`nf-test test tests/bismark/nftest/*` https://github.com/nf-core/methylseq/tree/3a37329ef99eeabd0685e64de7754dc7ce4bed92/tests/bismark/nftest

I don't think we need to wait for tags, it'll just be a CI hack.
:cowboy_hat_face: :rocket:

**Comment by nvnieuwk** [comment]
Ow damn that's genius! Currently I don't have any free time to put it together but I will surely expand the prototype when I have some more free time :)

**Comment by ivopieniak** [comment]
Hi @nvnieuwk , me and @aaron-fishman-achillestx have added a new feature to the nf-test which is junitXML output. This might useful feature for you if you are using CI for testing.

**Comment by aaron-fishman-achillestx** [comment]
ah cool @Emiller88 . You can use the main branch by compiling from source. Install maven, and then:
```
git clone git@github.com:askimed/nf-test.git
cd nf-test
mvn install
```

This will produce a `nf-test/target/nf-test.jar` file. To use it, update the `nf-test` bash script that is on you path to point to the new jar. First locate with `which nf-test`, and then modify the `APP_HOME` and `APP_JAR` variables at the top:
```
#!/bin/bash
APP_HOME="/PATH/TO/nf-test/target/"
APP_JAR="nf-test.jar"
APP_UPDATE_URL="https://code.askimed.com/install/nf-test"

set -e

....etc .
```

We use Bitbucket for our repo which parse junit out the box, but found this action: https://github.com/marketplace/actions/junit-report-action

**Comment by Emiller88** [comment]
That looks beautiful!

I'm going to throw together a `setup-nf-test` action as well, so that'll be handled there hopefully.

**Comment by nvnieuwk** [comment]
Awesome to see it all come together! `nf-test` keeps surprising me :partying_face:

**Comment by lukfor** [comment]
Hi all!

We just released nf-test 0.7.1 :rocket:

 This release includes junit support, YAML asserts and nested params. Thanks to @aaron-fishman-achillestx, @ivopieniak and @byb121 👍 

https://github.com/askimed/nf-test/releases/tag/v0.7.1

**Comment by lukfor** [comment]
> That looks beautiful!
> 
> I'm going to throw together a `setup-nf-test` action as well, so that'll be handled there hopefully.

Thanks, thats cool! It would be great to describe this action also in the nf-test documentation (see https://github.com/askimed/nf-test/issues/38).

**Comment by ivopieniak** [comment]
> Yep, I couldn't figure out how to download the main branch without a release. I'm also on the hunt for a good junitxml report GitHub action.
> 
> I did set up taps on methylseq https://github.com/nf-core/methylseq/blob/dev/.github/workflows/ci.yml#L73-L76

Hi @Emiller88 , I am not sure how do you exactly intend to use the TAP output in the GitHub Actions, however what we tend to use is to parse TAP output is [prove](https://docs.mojolicious.org/prove) which generates well-parsed and consistently looking output directly in the terminal.

**Comment by Emiller88** [comment]
Nice! I was just tossing it in there because output for CI help new years figure out why the CI is :x:.

Looks like @lukfor just cut 0.7.1, so I'm not pressed for setup-nf-test, but I'll definitely PR it to the docs.

**Comment by ivopieniak** [comment]
Congrats on getting in the methylseq @Emiller88 ! Just out of interest - what are your plans for nf-test going forward? Are you hoping to expand it to other pipelines as well? If it is helpful for you we have added more features to the codebase:
* assertAll
* order agnostic List comparison against complex data structures (with detailed examples in documentation)
* Improved automatic test discovery options

**Comment by Emiller88** [comment]
Let's just close this in favor of https://github.com/orgs/nf-core/projects/43/views/2
