### ISSUE TITLE
new subworkflow: fastq_align_bwa 

### ISSUE THREAD

**Issue by JoseEspinosa** [nf-core/modules#2412]
### Is there an existing subworkflow for this?

- [X] I have searched for the existing subworkflow

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this subworkflow, I added myself to the `Assignees` to facilitate tracking who is working on the subworkflow

**Comment by Emiller88** [comment]
https://github.com/nf-core/nascent/tree/dev/subworkflows/local/align_bwa

**Comment by JoseEspinosa** [comment]
Thanks! 😄 We also have it in the chipseq and atacseq pipelines: https://github.com/nf-core/chipseq/blob/master/subworkflows/nf-core/align_bwa_mem.nf  
that's the reason why I wanted to create it. However, just found the `FASTQC_ALIGN_DNA` implemented on [this](https://github.com/nf-core/modules/pull/2201) PR and was wondering whether we should favor it or whether it is fine to keep both of them in the repo 🤔

**Comment by JoseEspinosa** [comment]
Just realized that `FASTQ_ALIGN_DNA` does not include the `BAM_SORT_STATS_SAMTOOLS` part so I guess it's ok to also have this subworkflow provided that at least 3 pipelines are using it.
