### ISSUE TITLE
len() function in deseq2/differential is not found

### ISSUE THREAD

**Issue by WackerO** [nf-core/modules#2419]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

@jonath

In deseq2/differential:deseq_de.R, l155, the `len(missing_samples)` function is not recognized and throws an error (`Error in len(missing_samples) : could not find function "len",`) it should just be replaced with `length()`. (This happens when the input files are not correct, i.e. some samples are missing from the count table.)

**Comment by pinin4fjords** [comment]
Thanks @WackerO , sounds like an easy fix- could you maybe just raise the PR?

**Comment by WackerO** [comment]
Yes, will do that in a moment
