### ISSUE TITLE
MINIMAP2_ALIGN and _INDEX have different versions of minimap in their default containers

### ISSUE THREAD

**Issue by awgymer** [nf-core/modules#2444]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

The `MINIMAP2_INDEX` and `MINIMAP2_ALIGN` containers are different, as `_ALIGN` uses `samtools` for `bam` generation and needs a `mulled` container, whilst `_INDEX` uses only `minimap2`. 

This has resulted in the two modules having different versions of `minimap2` by default. This does not seem ideal if the intention is to pass the output of `_INDEX` into `_ALIGN`.

```
MINIMAP2_ALIGN:
  minimap2: 2.24-r1122
MINIMAP2_INDEX:
  minimap2: 2.21-r1071
```

I would propose either using the same `mulled` container for `_INDEX` despite not requiring `samtools`?

```console
│ minimap2/align              │ https://github.com/nf-core/modules.git │ 5850432aab24a1924389b660adfee3809d3e60a9 │ Allow self-alignment of reads in minimap2 (#2342) │ 2022-10-21 │
│ minimap2/index              │ https://github.com/nf-core/modules.git │ 5e34754d42cd2d5d248ca8673c0a53cdf5624905 │ Restructure nf-core/modules repo (#2141)          │ 2022-10-04 │
```

**Comment by muffato** [comment]
That would work, but you can also simply bump up the minimap2 version in `MINIMAP2_INDEX`. In Bioconda, minimap2 2.24 resolves to 2.24-r1122, so the same as in the mulled container.

Regardless of the solution we choose, there need to be some comments in both files to remind people that both modules need to be on the same version of minimap2
