### ISSUE TITLE
[FEATURE] Update mulled containers in BBmap to use samtool 1.16.1

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/modules#2504]
### Is your feature request related to a problem? Please describe

As the title states. 

In an earlier attempt, conda & docker worked but singularity kept failing, see here: https://github.com/nf-core/modules/actions/runs/3454818988/jobs/5766755071

Mulled container in question:

```
conda (params.enable_conda ? "bioconda::bbmap=38.92 bioconda::samtools=1.16.1 pigz=2.6" : null)
    container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
        'https://depot.galaxyproject.org/singularity/mulled-v2-008daec56b7aaf3f162d7866758142b9f889d690:0a5e270231c37fbf302accd3df4b815a27134526-0' :
        'quay.io/biocontainers/mulled-v2-008daec56b7aaf3f162d7866758142b9f889d690:0a5e270231c37fbf302accd3df4b815a27134526-0' }"

```

**Comment by SPPearce** [comment]
@FriederikeHanssen , can you update the mulled container to a later version?
The different subtools are already different versions (including 38.98, ahead of the 38.92 in that mulled container), would be good to be consistent. Looks like the bbmap version is now 39.01, but 38.98 would be fine.
I don't really understand how to update the mulled container to do it myself.

**Comment by FriederikeHanssen** [comment]
I can take a look later if you give me all the specs. But also to spread the knowledge on how to create these containers:
It is just adding a line into this tsv file with the new version number and opening a PR. Bjoern Gruening then merges it for you and the containers appear ✨ :

https://github.com/BioContainers/multi-package-containers/blob/master/combinations/hash.tsv

**Comment by FriederikeHanssen** [comment]
no in my experience it takes about 24h to get in one of his review cycles and have it merged (as long as CI passes). On rare occasions I dropped a line in the biocontainers gitter if it took a long time. But usually the container is there in a day.

**Comment by SPPearce** [comment]
Ok, I'll try and get the versions bumped once that happens then.

**Comment by SPPearce** [comment]
@FriederikeHanssen, sorted this for you.

**Comment by FriederikeHanssen** [comment]
Awesome! Thank you 🙏
