### ISSUE TITLE
new module: cellranger/multi

### ISSUE THREAD

**Issue by ggabernet** [nf-core/modules#2515]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by ddiep-altoslabs** [comment]
Hi!, Gisela, are you still working on creating this module?

**Comment by ggabernet** [comment]
Hi Dinh,

thanks for your message, I was gonna work on this but the some other things came in between. The main blocker at the moment is including test data for the module in the test-datasets repository.

**Comment by dinhdiep** [comment]
Hi! Gisela,

Thanks for still working on this!

I just created a pull request for the test-datasets repository [here](https://github.com/nf-core/test-datasets/pull/712)

Best,

Dinh

**Comment by Aratz** [comment]
Hi! What's the current status with the cellranger multi module? Our bioinformaticians would be very interested in seeing this feature included in [nf-core/scrnaseq](https://github.com/nf-core/scrnaseq). We will participate in the Hackathon next week from the Stockholm node and would love to help out with this.

**Comment by heylf** [comment]
I am working on the cellranger-arc module / subworkflow for scrnaseq during the Hackathon.

**Comment by klkeys** [comment]
a recent [test dataset](https://github.com/nf-core/test-datasets/tree/modules/data/genomics/homo_sapiens/illumina/10xgenomics/cellranger_vdj) was added for `cellranger vdj` (https://github.com/nf-core/modules/pull/3033)

I only used the V(D)J FASTQs but the source from 10X includes GEX FASTQs

it wouldn't be hard to add them, just need to aggressively subsample the reads

**Comment by klkeys** [comment]
happy for any feedback: #3229

still a work in progress; as Gisela notes, it needs test data first

**Comment by klkeys** [comment]
forgot to note: `cellranger multi` test data from https://github.com/nf-core/test-datasets/pull/848 are ready to use
