### ISSUE TITLE
Deprecated test data

### ISSUE THREAD

**Issue by KevinMenden** [nf-core/modules#254]
This issue lists the remaining test datasets that couldn't be addressed in https://github.com/nf-core/modules/pull/249 but should be removed from the `generic` folder and replaced with suitable data in the `genomics` folder.

- [x] 'a.gff3.gz': bgzipped gff3 file currently necessary for TABIX test
- [x] ~bam~
    - [x] ~'test.paired_end_methylated.sorted.bam': methylated bam file currently necessary for methyldackel~
- [ ] bedgraph: bedgraph files for seacr
- [x] ~'dummy_file.txt': a dummy file for whenever that is required~
- [ ] fasta: additional fasta files currently necessary for ~methyldackel and~ STAR
- [ ] fastq: additional fastq files currently necessary for STAR
- [ ] gtf: additional gtf file for STAR
- [ ] vcf: several VCF files for tools using those, will be removed in the future
- [ ] 'test.txt.gar.gz' exemplary tar file for the untar module

We can replace those files one by one and mention it here.

**Comment by drpatelh** [comment]
I believe this is safe to close now @KevinMenden? 🙂
