### ISSUE TITLE
new module: SALSA2

### ISSUE THREAD

**Issue by diegomics** [nf-core/modules#2570]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

tool: https://github.com/marbl/SALSA

**Comment by scorreard** [comment]
Hi! I will work on this module, feel free too reach out to me here or on nf-core slack if needed

**Comment by scorreard** [comment]
https://github.com/scorreard/modules/tree/newmodule_salsa2

**Comment by mahesh-panchal** [comment]
Just a note that the test data only needs to ensure the software runs through. The output doesn't need to be sensible.

**Comment by mahesh-panchal** [comment]
I ran your code ( with a few changes ) and just using 
```
    input = [
        [ id:'test', single_end: false ], // meta map
        file(params.test_data['sarscov2']['genome']['genome_fasta'], checkIfExists: true),
        file(params.test_data['sarscov2']['genome']['genome_fasta_fai'], checkIfExists: true)
    ]
    bed = file(params.test_data['sarscov2']['genome']['test_bed'], checkIfExists: true)
```
for test input works fine. 

(also note, the tool is not multi-threaded, there is a DEEPVARIANT setting in the config, and `-o` produces a folder, so you'll need to extract the files out of it.)

**Comment by scorreard** [comment]
Ready for review : https://github.com/nf-core/modules/pull/2625

**Comment by scorreard** [comment]
Done
