### ISSUE TITLE
new module: MitoHiFi

### ISSUE THREAD

**Issue by mahesh-panchal** [nf-core/modules#2571]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

Tool: https://github.com/marcelauliano/MitoHiFi

**Comment by verku** [comment]
I implemented the tool `findMitoReference.py` which is part of MitoHiFi as a separate module. It is now ready for review: https://github.com/nf-core/modules/pull/3135

**Comment by ksenia-krasheninnikova** [comment]
Working on the main mitohifi.py module

**Comment by ksenia-krasheninnikova** [comment]
Main mitohifi functionality was implemented in [PR 3573](https://github.com/nf-core/modules/pull/3573)

**Comment by ksenia-krasheninnikova** [comment]
Closing issue
