### ISSUE TITLE
BWA_MEM and BWAMEM2_MEM pass too many indexs

### ISSUE THREAD

**Issue by edmundmiller** [nf-core/modules#262]
## Description of the bug

When using these modules with aws-igenomes the mem fails, because the below lines pick up multiple indexes

```
INDEX=`find -L ./ -name "*.amb" | sed 's/.amb//'`
```

This line was introduced by @drpatelh 

Some more background
```s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/genome.fa
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/genome.fa.amb
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/genome.fa.ann
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/genome.fa.bwt
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/genome.fa.pac
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/genome.fa.sa
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/version0.5.x/genome.fa
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/version0.5.x/genome.fa.amb
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/version0.5.x/genome.fa.ann
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/version0.5.x/genome.fa.bwt
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/version0.5.x/genome.fa.pac
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/version0.5.x/genome.fa.rbwt
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/version0.5.x/genome.fa.rpac
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/version0.5.x/genome.fa.rsa
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/version0.5.x/genome.fa.sa
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/version0.6.0/genome.fa
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/version0.6.0/genome.fa.amb
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/version0.6.0/genome.fa.ann
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/version0.6.0/genome.fa.bwt
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/version0.6.0/genome.fa.pac
s3://ngi-igenomes/igenomes/Staphylococcus_aureus_NCTC_8325/NCBI/2006-02-13/Sequence/BWAIndex/version0.6.0/genome.fa.sa
```
Note the `version0.6.0` and `version0.5.x` 

## Steps to reproduce

Steps to reproduce the behaviour:

I don't really have good steps to reproduce inside of modules right now.

**Comment by MaxUlysse** [comment]
The way they do it in the GATK4 pipelines is to pass the reference.fasta file name as a string.
We could pass the value as an additional entry, or have that in the meta map.

**Comment by drpatelh** [comment]
This is something that will require a fix on AWS iGenomes. We need to provide the full path to directory containing the index and not a top-level directory. That should fix it. Fancy fixing this in the pipeline template @Emiller88 on the `dsl2_template` branch?

**Comment by drpatelh** [comment]
Ok. Deleted the last comment because it was getting messy but I see the problem now...unless we default to `find` the first instance of the index in that structure? Is that possible? Realistically, nesting indices like that is the actual problem here and should be avoided in my opinion...is this only a problem for some genomes?

**Comment by MaxUlysse** [comment]
I'm sure we can hack the `find` line., but wouldn't it be easier and less hacky to have an extra value?

**Comment by drpatelh** [comment]
We could but how would having an extra fasta file being staged here help? We would still have the same issues with paths no? I have to say the biggest advantage of passing around and using `find` is that you can provide the entire index in a directory (tarred or untarred) and the pipeline will deal with it appropriately without having to worry about genome fasta prefixes? e.g. [here](https://github.com/nf-core/rnaseq/blob/3643a94411b65f42bce5357c5015603099556ad9/modules/local/subworkflow/prepare_genome.nf#L125-L126)

**Comment by drpatelh** [comment]
Yup, but that name would still be found 3 times in the example structure above?

**Comment by MaxUlysse** [comment]
No, because I would only pass `BWAIndex/genome.fa`.

To be honest I would only pass `genome.fa`, and use `{}` to cover all extension from the indices... but that's another debate...

**Comment by drpatelh** [comment]
Ok. Then I think we will still need some sort of hack in order to use tarred directories containing indices? That is where the `find` is the most useful because it finds the appropriate files for you. I agree we need to do something about this though.

**Comment by MaxUlysse** [comment]
I'm guessing the `UNTAR_STAR_INDEX` process (or any similar) could give out the indices, that we can collect to use as only one channel, and the value for the `genome.fa` or whatever string it should be.
So it could work

**Comment by Emiller88** [comment]
I think it could be handled in the prepare genome workflow. We could also just throw a `cut` in there to take the first genome it finds.

**Comment by Emiller88** [comment]
I think that could work. 

To be honest though I don't know why the `INDEX` was introduced, so if someone could link that discussion I might be more help.

**Comment by MaxUlysse** [comment]
> I think that could work.
> 
> To be honest though I don't know why the `INDEX` was introduced, so if someone could link that discussion I might be more help.

I think it was @drpatelh

**Comment by drpatelh** [comment]
Yep, I did it without permission because it made sense at the time and it solved quite a few problems with passing the index around and standardising the use of compressed directories too. To be fair, the only edge case is the one you pointed out @Emiller88 where you can have different indices nested in the same directory - I suspect this scenario is going to be extremely rare and if so then using the index in the top-level directory is a good shout or the user just re-organises their indices 🤷🏽 

As we have discussed at length already, passing the `fasta` file in addition to the index is not a satisfactory solution because users can also call their custom indices whatever they want which means using the base name of the fasta isn't sufficient. This is why using a `find` made sense to deal with whatever people chose to call the index files. 

I will have another play with this whilst try to re-prep the rnaseq pipeline for a release.

**Comment by MaxUlysse** [comment]
I think we can have a `bwaindex.first.basename()` or something like that to get the actual fasta name, and add that to the map in case of user specified indices

**Comment by drpatelh** [comment]
Ok. So if you are able to get a working prototype together where we *don't* have to pass the fasta file to the alignment process and where we can use `.tar.gz` directories for the index then that would be great @MaxUlysse

**Comment by MaxUlysse** [comment]
I'll look into it.

**Comment by maxulysse** [comment]
cc #627

**Comment by SPPearce** [comment]
Closing as outdated
