### ISSUE TITLE
new module: openms/cometadapter

### ISSUE THREAD

**Issue by marissaDubbelaar** [nf-core/modules#292]
I think it would be good to have a module for [openms](https://bioconda.github.io/recipes/openms-meta/README.html)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by louperelo** [comment]
Hi there!

We’ve noticed there hasn’t been much activity here. Are you still planning on working on this?
If not, you can ignore this message and we’ll close your PR in about 2 weeks

Cheers
the nf-core maintainers
