### ISSUE TITLE
new module: custom/get_software_versions | Demo module for local scripts

### ISSUE THREAD

**Issue by grst** [nf-core/modules#294]
Implement the `get_software_version` process used in all pipelines as a DSL2 module. 
This serves as a test-case to figure out a way to deal with custom scripts (traditionally stored in the `bin` directory of the main workflow) in nf-core/modules. 

 * Implementation of get_software_versions in the rnaseq pipeline: https://github.com/nf-core/rnaseq/blob/master/modules/local/process/get_software_versions.nf
 * Nextflow issue discussing direct support for custom scripts in DSL2 modules: https://github.com/nextflow-io/nextflow/issues/1798

**Comment by grst** [comment]
I tried: 

 * adding `bin/my_script.sh` to the module directory and invoking it with `${moduleDir}/bin/my_script.sh`. 
This works in principle, but nextflow does not take the file into account for caching. I.e. modifying the files does not 
invalidate the cache. 
 * modifying the `PATH` variable in the `script` section -> does not work

**Comment by grst** [comment]
See also 
https://github.com/nextflow-io/nextflow/issues/1798

**Comment by jasmezz** [comment]
Hi there!

We’ve noticed there hasn’t been much activity here. Are you still planning on working on this?
If not, you can ignore this message and we’ll close your PR in about 2 weeks

Cheers
the nf-core maintainers
