### ISSUE TITLE
new module: kraken2/build

### ISSUE THREAD

**Issue by sarah-buddle** [nf-core/modules#2953]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by alxndrdiaz** [comment]
Just a few comments. According to the [kraken2 documentation ](https://github.com/DerrickWood/kraken2/blob/master/docs/MANUAL.markdown#custom-databases): 

1.  The first step is to download the NCBI taxonomy files  with `kraken2-build --download-taxonomy` , this might take some time since the files are quite large (as far as I remember). 
2. Both reference genomes can be installed or the user can add genomes from a local directory. The first option seems easier to implement.
3. After you run  `kraken2-build --build` and `bracken-build` you also need to run `kraken2-build --clean` to remove files that are not used by `kraken2` during classification.

A subworflow could be used instead of a single module. In this subworkflow there could be a module for each step: download taxonomy, add libraries/genomes, kraken2-build, bracken-build, and clean.

**Comment by jfy133** [comment]
@alxndrdiaz did you make progress on this? I would like to have this for nf-core/createtaxdb, but you've already started I can leave it for you to finish.

**Comment by alxndrdiaz** [comment]
@jfy133 I didn't add any module yet. But I am happy to contribute with the kraken2 build and bracken build modules. How do you plan to handle the NCBI taxonomy files (there is  a kraken2 command for that but they  could be stored elsewhere and then only use wget or curl before building the database)?

**Comment by alxndrdiaz** [comment]
@jfy133 I just figured out that first we need to add genomes to the database  (`kraken2-build --add-to-library)` before the kraken2 build and bracken build steps, so I am working on that first.

**Comment by jfy133** [comment]
I think that would just require two invocation of the same module, right? It's just switching out a flag IIRC

**Comment by alxndrdiaz** [comment]
> I think that would just require two invocation of the same module, right? It's just switching out a flag IIRC

That's right add FASTA files the command is `kraken2-build --add-to-library $FASTA --db $DBNAME` and to build the database once the files had been added `kraken2-build --build --db $DBNAME ` . In fact I am struggling more with adding the tests using nf-test.

**Comment by jfy133** [comment]
What's the issue with the nf-test? I have two days of trains across Western Europe so maybe I can help (from my phone anyway). Feel free to message me on slack :)

**Comment by jfy133** [comment]
OK we have add but not build, @alxndrdiaz will you continue with build or should I do this?

**Comment by alxndrdiaz** [comment]
> OK we have add but not build, @alxndrdiaz will you continue with build or should I do this?

@jfy133  I'll do it.

**Comment by alxndrdiaz** [comment]
@jfy133 Already linked the PR. First error is related to expected file names for `.dmp` taxonomy files: 
```

│   Command error:                                                                                                                                               │
│     Creating sequence ID to taxonomy ID map (step 1)...                                                                                                        │
│     lookup_accession_numbers: expected TAB not found in taxonomy/prot.accession2taxid                                                                          │
│     Found 0/13 targets, searched through 1 accession IDs, search complete.                                                                                     │
│     lookup_accession_numbers: 13/13 accession numbers remain unmapped, see unmapped.txt in DB directory                                                        │
│     Sequence ID to taxonomy ID map complete. [0.009s]                                                                                                          │
│     Estimating required capacity (step 2)...                                                                                                                   │
│     Estimated hash table requirement: 157988 bytes                                                                                                             │
│     Capacity estimation complete. [0.006s]                                                                                                                     │
│     Building database files (step 3)...                                                                                                                        │
│     build_db: error opening taxonomy//nodes.dmp: No such file or directory    
```
Expected file names should be: `names.dmp` and `nodes.dmp`. Then I will first try to rename these files in the add module.
