### ISSUE TITLE
Use remote repos with include statement

### ISSUE THREAD

**Issue by drpatelh** [nf-core/modules#3]
Need to test and possibly work out a way to use a remote git repo with the `include` statement 
e.g. 
```
modules_base = "https://raw.githubusercontent.com/nf-core/modules/${params.module_version}"
include "${modules_base}" params(params)
```

**Comment by drpatelh** [comment]
This will no longer be an issue with the proposed implementation in https://github.com/nf-core/modules/issues/8 because modules will be pre-installed into the pipeline repo. Is this ok to close @ewels ?

**Comment by ewels** [comment]
Yup 👍 Although I still think that this would be very elegant, Paolo's recommendation was "never do this" and I agree it does cause a set of problems of its own. As you say, #8 is an alternative approach which we will use instead.
