### ISSUE TITLE
bump cellranger version

### ISSUE THREAD

**Issue by grst** [nf-core/modules#3011]
Could someone with access to the nf-core docker (@apeltzer ?) please rebuild the cellranger docker image with version 7.1 and bump the version in the respective modules? 

@apeltzer, Ideally we can get this in the 2.2.0 release of scrnaseq.

**Comment by apeltzer** [comment]
Yeah I am on it...

**Comment by apeltzer** [comment]
Pushed, nfcore/cellranger:7.1.0 is available now - will also open a separate PR with you as reviewewer https://github.com/nf-core/modules/pull/3013

**Comment by grst** [comment]
Awesome, thanks!
