### ISSUE TITLE
new module: HTSeq/count

### ISSUE THREAD

**Issue by bozmik** [nf-core/modules#3081]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by pinin4fjords** [comment]
What's the reason for this over [featureCounts](https://github.com/nf-core/modules/tree/master/modules/nf-core/subread/featurecounts)? The results are identical (with some very minor differences to do with paired-end handling IIRC).

**Comment by pinin4fjords** [comment]
My point was just that the featureCounts results are _identical_ in most cases to the output of htseq-count, and that in the absence of functional reasons for not doing so, you should consider using featureCounts instead to produce a quicker and less resource-intensive pipeline. 

But I'm sure nobody will object to the addition if there are good reasons for it that I'm missing.

**Comment by bozmik** [comment]
Yeah, thanks for the comment and the recommendation. For sure we will take this into account for additional improvements to the pipeline. But for now, the priority for us is to create a DSL2 version of the dualrnaseq pipeline using the same tools which were implemented in the DSL1 version (https://nf-co.re/dualrnaseq).
