### ISSUE TITLE
new module: DoRothEA

### ISSUE THREAD

**Issue by pinin4fjords** [nf-core/modules#3085]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by pinin4fjords** [comment]
see https://github.com/nf-core/differentialabundance/issues/99

**Comment by pinin4fjords** [comment]
Could follow temlate-driven implementation pattern used in deseq2/differerential etc

**Comment by grst** [comment]
I suggest to close this and implement decoupleR/decoupler-py which is now recommended by the Saezlab and is more generic (i.e. decoupler is the method for testing gene sets, while Dorothea is just one of many reference databases)

**Comment by pinin4fjords** [comment]
Like [this](https://github.com/nf-core/modules/blob/master/modules/nf-core/decoupler/decoupler/main.nf)?
