### ISSUE TITLE
new module: thermorawfileparser

### ISSUE THREAD

**Issue by rolivella** [nf-core/modules#3105]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by jonasscheid** [comment]
@rolivella Can you ping me if you have a PR on this? We would use this module too

**Comment by rolivella** [comment]
@jonasscheid it was almost done during the past nf-core hackathon 2023: 

https://github.com/nf-core/modules/pull/3218#discussion_r1151928786
