### ISSUE TITLE
fastp: optional param specifying adapter file for trimming 

### ISSUE THREAD

**Issue by antunderwood** [nf-core/modules#318]
## Is your feature request related to a problem? Please describe
Add the ability for the fastp module to specify an optional adapter file for adapter trimming

## Describe the solution you'd like
Have an optional input using the method described here
https://github.com/nextflow-io/nextflow/issues/1694#issuecomment-789334369

## Describe alternatives you've considered
Passing adapter sequences in as strings

**Comment by louperelo** [comment]
This issue has been resolved with PR #2400
