### ISSUE TITLE
new module: fgbio/collectduplexseqmetrics

### ISSUE THREAD

**Issue by FerriolCalvet** [nf-core/modules#3257]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by famosab** [comment]
@georgiakes Do you have a PR you could link?

**Comment by georgiakes** [comment]
@famosab Just created one. Sorry for the delay. If you could also review, that would be great :)
