### ISSUE TITLE
Spades test.yml seems to not be calling the correct test

### ISSUE THREAD

**Issue by pericsson** [nf-core/modules#335]
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/module documentation](https://github.com/nf-core/modules/blob/master/README.md)

## Description of the bug

The [test.yml](https://github.com/nf-core/modules/blob/master/tests/software/spades/test.yml#L46) does not seem to point to the correct test workflow `test_coronospades_paired_end `, instead the test workflow `test_coronospades_single_end ` seems to be called two times and generating the same md5sums.

## Expected behaviour

We can change the test that is performed [here](https://github.com/nf-core/modules/blob/master/tests/software/spades/test.yml#L46) to point to the correct test workflow `test_coronospades_paired_end ` and update the md5sums.

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the module
- [ ] The `.nextflow.log` file

**Comment by drpatelh** [comment]
Ping @JoseEspinosa 😆 ! Thanks @pericsson 😎
