### ISSUE TITLE
new modules for `cellranger-atac`

### ISSUE THREAD

**Issue by klkeys** [nf-core/modules#3437]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs, and one does exist!

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

enabling this support will require 3 separate modules under the `cellranger-atac` banner:
* `mkfastq`
* `mkref`
* `count`

**Comment by wonhwang1** [comment]
Closed by #3575
