### ISSUE TITLE
new module: SALMON/ALEVIN (scRNAseq)

### ISSUE THREAD

**Issue by ggabernet** [nf-core/modules#347]
I think it would be good to have a module for [SALMON/ALEVIN](https://bioconda.github.io/recipes/salmon/README.html)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

Example process:
https://github.com/nf-core/scrnaseq/blob/13b7b90fb452108b9423523402a140331761a672/main.nf#L437

**Comment by KevinMenden** [comment]
Working but outdated version on this PR:
https://github.com/nf-core/modules/pull/397

Only the test data needs to be updated.

**Comment by apeltzer** [comment]
Guess we should consider directly addin `alevin-fry` instead 👍🏻 Similar to what kallisto-bustools did with `kbtools`, this looks like the most up2date way of running this sort of analysis. 

https://alevin-fry.readthedocs.io/en/latest/collate.html

**Comment by louperelo** [comment]
Related to closed PR #1420
