### ISSUE TITLE
new module: HAPPY/REPPY

### ISSUE THREAD

**Issue by LlaneroHiboreo** [nf-core/modules#3476]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by LlaneroHiboreo** [comment]
done

**Comment by Emiller88** [comment]
@LlaneroHiboreo I don't see this module in nf-core/modules and there's nothing linked to this. If you're not planning on doing it and that wasn't a mistake, close it again as not planned. The “done” comment is confusing me.

**Comment by LlaneroHiboreo** [comment]
not planned
