### ISSUE TITLE
new module: CNVNator

### ISSUE THREAD

**Issue by yocra3** [nf-core/modules#355]
I think it would be good to have a module for [cnvnator](https://bioconda.github.io/recipes/cnvnator/README.html)

- [X] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [X] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [X] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by cmatKhan** [comment]
What is the status of this? I'd like to use cnvnator in a local pipeline. It there is a proposed module already written, I'd like to contribute to it if I can.

**Comment by yocra3** [comment]
Hi,

I created the issue in the hackathon of 2021 but I did not work on this. I do not know how CNYpytor is related to CNVnator. However, if it is an updated implementation, it can make sense to close this issue and continue with CNVpytor. Anyway, I cannot work on this issue at the moment, so you are free to assign yourself the issue and continue as you prefer.

Bests!

**Comment by cmatKhan** [comment]
CNVPytor is the original authors port to python rather than whatever CNVnator was in. I don't think CNVnator is maintained anymore. at least, the authors recommend using CNVpytor
