### ISSUE TITLE
new module: kallisto/quant

### ISSUE THREAD

**Issue by ggabernet** [nf-core/modules#359]
I think it would be good to have a module for [kallisto/quant](https://bioconda.github.io/recipes/kallisto/README.html)

- [ ] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [ ] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [ ] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by anoronh4** [comment]
Just wondering what the status is for this module! I noticed there hasn't been any development in over a year. I'm happy to take a stab at it as well.
