### ISSUE TITLE
new module: gubbins

### ISSUE THREAD

**Issue by avantonder** [nf-core/modules#362]
I think it would be good to have a module for [Gubbins](https://bioconda.github.io/recipes/gubbins/README.html)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by rpetit3** [comment]
This was added https://github.com/nf-core/modules/pull/377
