### ISSUE TITLE
Fix failing tests after data restructuring

### ISSUE THREAD

**Issue by KevinMenden** [nf-core/modules#363]
This is a list of all module tests that we need to get the tests passing for again: Please assign yourself by editing this issue:

- [x] bowtie2/align (assigned @JoseEspinosa )
- [x] bowtie2/build_test (assigned @JoseEspinosa )
- [x] bwameth/align (assigned @JoseEspinosa )
- [x] bwameth/index (assigned @JoseEspinosa )
- [x] multiqc (assigned @JoseEspinosa )
- [x] gffread (assigned @KevinMenden )
- [x] sequenzautils/gcwiggle (assigned @KevinMenden )
- [x] homer/annotatepeaks (assigned @KevinMenden )
- [ ] bandage/image (assigned @KevinMenden )
- [x] seqwish/induce (assigned @KevinMenden )
- [x] salmon/index (assigned to @BatoolMM )
- [x] salmon/quant (assigned to @BatoolMM)
- [x] trimgalore (@grst)
- [x] picard/markduplicates  (@grst)
- [x] picard/mergesamfiles  (@grst)
- [x] picard/collectmultiplemetrics  (@grst)
- [x] picard/collectwgsmetrics  (@grst)
- [x] minia
- [x] pangolin (@rpetit3)
- [x] minimap2/align (@yuukiiwa)
- [x] vcftools (@KevinMenden )
- [x] bismark/report  (@KevinMenden )
- [x] bismark/align  (@KevinMenden )
- [x] bismark/genomepreparation  (@KevinMenden )
- [x] bismark/summary  (@KevinMenden )
- [x] bismark/deduplicate  (@KevinMenden )
- [x] bismark/methylationextractor  (@KevinMenden )
- [x] untar (@JoseEspinosa )
- [x] cat/fastq (@JoseEspinosa )
- [x] blast/blastn (@rpetit3)
- [x] blast/makeblastdb  (@rpetit3)
- [x] kraken2/run (@JoseEspinosa )
- [x] bedtools/genomecov (✔️ @drpatelh)
- [x] bedtools/slop (✔️ @drpatelh)
- [x] bedtools/merge (✔️ @drpatelh)
- [x] bedtools/getfasta (✔️ @drpatelh)
- [x] bedtools/sort (✔️ @drpatelh)
- [x] bedtools/complement (✔️ @drpatelh)
- [x] bedtools/intersect (✔️ @drpatelh)
- [x] bedtools/maskfasta (✔️ @drpatelh)
- [x] gunzip (@fullama)
- [x] preseq/lcextrap  (@rpetit3)
- [x] spades  (@rpetit3)
- [x] bwa/mem @FriederikeHanssen 
- [x] bwa/index @FriederikeHanssen 
- [ ] unicycler  (@rpetit3)
- [x] bwamem2/mem @FriederikeHanssen 
- [x] bwamem2/index @FriederikeHanssen 
- [x] bcftools/stats (assigned @Mark-S-Hill)
- [x] bcftools/isec (assigned @Mark-S-Hill)
- [x] bcftools/filter (assigned @Mark-S-Hill)
- [x] bcftools/consensus (assigned @Mark-S-Hill)
- [x] bcftools/mpileup (assigned @Mark-S-Hill)
- [x] bcftools/merge (assigned @Mark-S-Hill)
- [ ] star/align  (@rpetit3)
- [ ] star/genomegenerate  (@rpetit3)
- [X] tabix/tabix (@rpetit3)
- [X] tabix/bgzip (@rpetit3)
- [x] optitype  (@rpetit3)
- [x] samtools/view(assigned @arontommi )
- [x] samtools/stats(assigned @arontommi )
- [x] samtools/flagstat(assigned @arontommi )
- [x] samtools/faidx(assigned @arontommi )
- [x] samtools/mpileup(assigned @arontommi )
- [x] samtools/index(assigned @arontommi )
- [x] samtools/fastq(assigned @arontommi )
- [x] samtools/merge(assigned @arontommi )
- [x] samtools/sort(assigned @arontommi )
- [x] samtools/idxstats(assigned @arontommi )
- [x] stringtie (@yuukiiwa)
- [x] bowtie/align (@yuukiiwa)
- [x] bowtie/build_test (@yuukiiwa)
- [x] seqkit/split2 @FriederikeHanssen 
- [x] prokka (@fullama)
- [x] gatk4/createsequencedictionary (@suzannejin)
- [x] gatk4/variantfiltration (assigned @Mark-S-Hill)
- [x] gatk4/bedtointervallist (@suzannejin)
- [x] gatk4/samtofastq (@suzannejin)
- [x] gatk4/splitncigarreads (@suzannejin)
- [x] gatk4/fastqtosam (@suzannejin)
- [x] gatk4/revertsam (@suzannejin)
- [x] gatk4/mergebamalignment (@suzannejin)
- [x] gatk4/applybqsr (@suzannejin)
- [x] gatk4/baserecalibrator (@suzannejin)
- [x] gatk4/mergevcfs (@suzannejin)
- [ ] flash  (@rpetit3)
- [x] mosdepth (@rpetit3)
- [ ] seacr/callpeak (@rpetit3)
- [x] prodigal (@fullama)
- [x] quast  (@rpetit3)
- [x] cnvkit (@fullama)
- [x] ivar/consensus (@fullama)
- [x] ivar/variants (@fullama)
- [x] ivar/trim (@fullama)
- [x] fastp (✔️ @drpatelh)
- [x] allelecounter (@fullama)
- [x] cutadapt (@fullama)
- [x] fastqc (✔️ @drpatelh)
- [x] tiddit/sv (@rpetit3)
- [x] methyldackel/mbias (@rpetit3)
- [x] methyldackel/extract (@rpetit3)
- [x] qualimap/bamqc (@rpetit3)
- [x] ucsc/bed12tobigbed (@yuukiiwa)
- [x] ucsc/bedgraphtobigwig (@yuukiiwa)
- [ ] shovill  (@rpetit3)
- [x] adapterremoval (@pericsson)
- [ ] strelka/germline @FriederikeHanssen 
- [x] dsh/splitbed (@pericsson)
- [x] dsh/filterbed (@pericsson)

**Comment by drpatelh** [comment]
The disadvantage of closing an uber, super, large issue linked to a PR 😆

**Comment by KevinMenden** [comment]
I think we're pretty much done here, except for a few modules that don't have proper test data anyway :+1:

**Comment by grst** [comment]
Closed this in favor of https://github.com/nf-core/modules/issues/745.
