### ISSUE TITLE
can not pull bclconvert image

### ISSUE THREAD

**Issue by ludirm93** [nf-core/modules#3645]
https://github.com/nf-core/demultiplex/blob/67b846577346a9267e1f1292c0159cdf002e2186/modules/nf-core/bclconvert/main.nf#L5C16-L5C16

I am using test,singularity profile 

singularity pull  --name nf-core-bclconvert-4.0.3.img.pulling.1689310103408 docker://nf-core/bclconvert:4.0.3 does not work

singularity pull  --name nf-core-bclconvert-4.0.3.img.pulling.1689310103408 docker://nfcore/bclconvert:4.0.3 worked

Need to change "nf-core/bclconvert:4.0.3" to "nfcore/bclconvert:4.0.3"

**Comment by Emiller88** [comment]
@matthdsm moved this over from demultiplex, looks like there's a typo, as most nf-core images use `nf-core` and that's what the module is looking for, but in the readme it says `nfcore/` https://github.com/nf-core/modules/blob/f0b5571009ef2ab855f6cbc1a3b35cafad57df33/modules/nf-core/bclconvert/README.md?plain=1#L10-L16

**Comment by matthdsm** [comment]
The correct URL is `quay.io/nf-core/bclconvert`, as all images were moved from docker to quay.io.
The README needs fixing, although that's only for building the image

**Comment by matthdsm** [comment]
fixed in #3646
