### ISSUE TITLE
Move from paths-filter

### ISSUE THREAD

**Issue by edmundmiller** [nf-core/modules#3808]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

It's served us well, but we're hitting API limits.

Maybe we're able to pass it an API key through a secret?

Example in https://github.com/nf-core/modules/pull/3807

**Comment by Emiller88** [comment]
https://github.com/dorny/paths-filter/issues/108
https://github.com/dorny/paths-filter/issues/73

Hmm I don't think it's paths-filter, I think we're hitting it somewhere else, and I think it's just the first thing to hit the API...

**Comment by frouioui** [comment]
Hello @edmundmiller, using https://github.com/dorny/paths-filter/pull/133 I have been to alleviate the API rate limit issues we were hitting on https://github.com/vitessio/vitess.

**Comment by edmundmiller** [comment]
@frouioui Hey thanks for reaching out! I think @mirpedrol solved it in #4202

**Comment by dorny** [comment]
FYI: the @frouioui fix has been merged in https://github.com/dorny/paths-filter/pull/133
and included in [v3.0.1](https://github.com/dorny/paths-filter/releases/tag/v3.0.1) release.
