### ISSUE TITLE
Fix `single-end` and `paired-end` test tags

### ISSUE THREAD

**Issue by Emiller88** [nf-core/modules#390]
Thoughts? Should we do it?
```diff
 tags:
   - fastqc
-  - fastqc_single_end
+  - single_end
```
and
```diff
 tags:
   - fastqc
-  - fastqc_paired_end
+  - paired_end
```

The way the test tags works, the `-fastqc_single_end` is redundant. `pytest --tag "fastqc paired-end"` would run that specific test anyways.

Docs in case anyone is interested.
https://pytest-workflow.readthedocs.io/en/stable/#running-specific-workflows

**Comment by grst** [comment]
Do we  need that `single_end` and `paired_end` tags at all? 
Is there any situation in which we would not just run both tests by using the `fastqc` tag anyway?

**Comment by Emiller88** [comment]
I agree there isn't. Might as well leave them though if we're going to make them less redundant. You could run all the `paired_end` tags if you wanted to. I don't know why anyone would. If you were working on the fastqc paired-end test locally you'd just use `ytest --tag "fastqc paired-end"` to avoid running the single-end test.

**Comment by muffato** [comment]
The `single_end` and `paired_end` tags were removed in #2282
