### ISSUE TITLE
Pass meta to saveAs function to allow more flexible publish directory

### ISSUE THREAD

**Issue by wkang0** [nf-core/modules#394]
## Is your feature request related to a problem? Please describe
The current saveAs function only see one variable from meta: meta.id. It's impossible to customize the output directory by other information in meta such as group or sample. 

## Describe the solution you'd like
One possible solution is to add meta as an argument to saveAs function. Here is an example: 
https://github.com/wkang0/modules/commit/b2b723246964f7b97a9dd849a91582d2e4598063

## Describe alternatives you've considered
None

## Additional context
None

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/modules/pull/423
