### ISSUE TITLE
new module: checkqc

### ISSUE THREAD

**Issue by matrulda** [nf-core/modules#4011]
Module for running the https://github.com/Molmed/checkQC CLI. 

The aim is to include this in the nf-core/demultiplex pipeline: https://github.com/nf-core/demultiplex/issues/143

### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module
```[tasklist]
### Tasks
```

**Comment by matrulda** [comment]
Hi @rezaiiimohammad ! I was planning on working on this today. You too?

**Comment by rezaiiimohammad** [comment]
Hi. Yes, this project seems interesting to me. Is it convenience for you?

**Comment by matrulda** [comment]
The thing is I already started this task last hackathon: https://github.com/nf-core/modules/pull/4158 It is kind of complete, only need to fix the tests

**Comment by rezaiiimohammad** [comment]
Ok, thanks for informing me. I'll try another task.

**Comment by matrulda** [comment]
No worries :)
