### ISSUE TITLE
Why are branches that are out of date showing so many changes

### ISSUE THREAD

**Issue by Emiller88** [nf-core/modules#4094]
Example: https://github.com/nf-core/modules/pull/4079

I've only changed bowtie2 but it's running all of the ATAC-seq jobs because of the merge. I'm guessing #3969, and the merge? Probably taking up a ton of extra CI jobs, because branches are quickly getting out of date.

@nf-core/a-team

**Comment by Emiller88** [comment]
@JoseEspinosa I heard you might have run into the same thing

**Comment by mashehu** [comment]
It's a problem with `paths-filter`, we switched to using git instead of sending (100s) of github requests, and somehow the git diff it takes is not correct. @mirpedrol is working on it.

**Comment by JoseEspinosa** [comment]
Not me but @FloWuenne but we already reported it to the infrastructure team
