### ISSUE TITLE
new module: PIGZ

### ISSUE THREAD

**Issue by alessiovignoli** [nf-core/modules#4106]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by lrauschning** [comment]
🐷

**Comment by alessiovignoli** [comment]
when compressing using a separate module, most compression tools will automatically delete the input file.
This behaviour makes sense, as otherwise there would be no space savings when keeping the uncompressed and compressed file simultaneously.
However, it breaks nextflows paradigm by having the running of one module affect the output of an earlier step, potentially breaking the resume support.
For this reason, the MSA modules should natively produce compressed output that is then uncompressed as needed.


For this reason only the uncompress function of pigzip is implemented. 

As for the [gunzip module](https://github.com/nf-core/modules/blob/master/modules/nf-core/gunzip/main.nf#L28) where the original file is actually kept.
