### ISSUE TITLE
gffread nucleotide to protein

### ISSUE THREAD

**Issue by chriswyatt1** [nf-core/modules#4152]
### Is your feature request related to a problem? Please describe

`gffread` has many different functions, the one used in this module converts a gff file to gtf .
However `gffread` also converts an input gff file and a genome (fasta) into a protein.fasta file. This functionality is lacking.
I am happy to write up this module to add this, but am not sure which direction to follow

### Describe the solution you'd like

I assume this needs to be a new module (as the inputs/output types will be quite different). If we make this a new module, it will mean the gffread module for gff to gtf will need to have a subfolder name... Will this mess up everyones pipelines if I create a new subfolder?

gffread -y <proteins.fa> -g <genome.fa> <annoation.gff3>

### Describe alternatives you've considered

Are there other modules in nf-core that simply converts genome/annotation to protein fastas? or should I just combine gffread into the next module I want to make (orthofinder) so that I don't need to make a new gffread module (a bit of a messy option, I think, but would work).

**Comment by GallVp** [comment]
Hi @chriswyatt1 

I had the same thoughts and changed the current gffread module to close this gap. Can you kindly check that the current version satisfies your needs?

https://github.com/nf-core/modules/blob/master/modules/nf-core/gffread/main.nf

**Comment by chriswyatt1** [comment]
Yes @GallVp, all looks great. I can use it for my use case too now, thanks!
