### ISSUE TITLE
To checksum or not to checksum versions

### ISSUE THREAD

**Issue by edmundmiller** [nf-core/modules#4249]
I'm dropping this pull request in favor of #4240, I don't feel comfortable updating the checksums for modules that I did not create.

Then in general, I think checksumming `versions.yml` is a bad idea, and makes simple version bump pull requests (like this was supposed to be) hard to do.

_Originally posted by @heuermh in https://github.com/nf-core/modules/issues/3925#issuecomment-1781373444_
            
This is a good point that I had been thinking about. It prevents use from bumping the container versions automatically through renovate, and if the versions don't match the containers we have bigger problems.

Maybe we should just check for the existence of the `versions.yml`?

**Comment by mashehu** [comment]
too many cases where we ran into situations, where versions where updated in conda but not the container and vice-versa (espacially with mulled containers). for now snapshotting versions is the only thing against that, and we now require it also in linting for nf-test. Closing this issue therefore.
