### ISSUE TITLE
new module: trust4

### ISSUE THREAD

**Issue by Joaodemeirelles** [nf-core/modules#4307]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by ggabernet** [comment]
Hi @Joaodemeirelles ,

I would be also interested in having this module available? Have you started some work on it already? If so, would you be willing to open a PR so that we can collaborate on it? Also happy to review - get started with a first draft for it

**Comment by Joaodemeirelles** [comment]
> Hi @Joaodemeirelles ,
> 
> I would be also interested in having this module available? Have you started some work on it already? If so, would you be willing to open a PR so that we can collaborate on it? Also happy to review - get started with a first draft for it

Great! I'll make a draft with the module itself, but I think the biggest hurdle for me is how to add the test dataset, since it would be needed
