### ISSUE TITLE
new module: liftoff

### ISSUE THREAD

**Issue by GallVp** [nf-core/modules#4514]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by fischer-hub** [comment]
Hey @GallVp ! Is this still being worked on? Otherwise I'd be happy to help and add the liftoff module as part of the nf-core hackathon!

**Comment by GallVp** [comment]
Hi @fischer-hub 

It is sitting in my local repo. I'll push it here and tag you for review?
