### ISSUE TITLE
[BUG] fastqc module always expects compressed reads and certain read naming

### ISSUE THREAD

**Issue by asl** [nf-core/modules#457]
FastQC module contains the following:

```
        [ ! -f  ${prefix}_1.fastq.gz ] && ln -s ${reads[0]} ${prefix}_1.fastq.gz
        [ ! -f  ${prefix}_2.fastq.gz ] && ln -s ${reads[1]} ${prefix}_2.fastq.gz
        fastqc $options.args --threads $task.cpus ${prefix}_1.fastq.gz ${prefix}_2.fastq.gz
        fastqc --version | sed -e "s/FastQC v//g" > ${software}.version.txtc
```

This is bad in lots of different ways:
  * It expects the certain naming of left / right reads
  * Only .fastq.gz are supported

**Comment by drpatelh** [comment]
> It expects the certain naming of left / right reads
> Only .fastq.gz are supported

Nope. The process just soft-links the files files provided in `reads` which could be called `fq.gz` or whatever you want to call them. They are renamed here because it makes it much easier to render per-sample info in the MultiQC report.

**Comment by asl** [comment]
Here is the fastqc cmdline:
```
        fastqc $options.args --threads $task.cpus ${prefix}_1.fastq.gz ${prefix}_2.fastq.gz
```

What I'm missing here? How I can have plain FASTQ here? Or, say, foo_R1.fastq.gz?

**Comment by drpatelh** [comment]
Yup. But this is just running the command on the "soft-linked fastq files" not the original input fastq file. You can't have plain fastq because we are actively discouraging the use of unzipped fastq files to be more efficient with storage as much as possible. Let me see if I can dig out the result of  running this in a pipeline for real.

**Comment by drpatelh** [comment]
```console
#!/bin/bash -ue
[ ! -f  WT_REP2_1.fastq.gz ] && ln -s SRR6357072_1.fastq.gz WT_REP2_1.fastq.gz
[ ! -f  WT_REP2_2.fastq.gz ] && ln -s SRR6357072_2.fastq.gz WT_REP2_2.fastq.gz
fastqc --quiet --threads 2 WT_REP2_1.fastq.gz WT_REP2_2.fastq.gz
fastqc --version | sed -e "s/FastQC v//g" > fastqc.version.txt
```

**Comment by asl** [comment]
Well, this is universal module. So, I'd expect it to be universally usable and not restrict the usage for some particular reason. There might be multiple reasons why the input is not compressed. E.g. if the input is the result of some filtering / trimming / preprocessing.

**Comment by drpatelh** [comment]
It is still universally usable except for instances that require uncompressed fastq files. If it isn't compressed by a given process then it should be e.g. https://github.com/nf-core/modules/blob/f7e3b8260ceeb6739093aec6f12d86b99cf7f799/software/kraken2/run/main.nf#L49 and then passed to this process. We have to start somewhere by enforcing these sorts of best practices...

**Comment by asl** [comment]
It does not make much sense, frankly speaking and in many cases it's a waste of resources first to compress the reads and then to decompress by any other tool in the pipeline. Remember that one cannot read compressed FASTQ files in parallel and our experience shows that in many cases simply decompressing the reads become a significant bottleneck as this process is inherently CPU bound and single threaded.

And again, my point is that it's up to pipeline to decide what to do with the input / output data and module should not enforce anything here, it's completely against the whole philosophy of modular structures. 

We will need to maintain a fork of FastQC module due to such limitation. And probably some other modules as well due to this.

**Comment by drpatelh** [comment]
> It does not make much sense, frankly speaking and in many cases it's a waste of resources first to compress the reads and then to decompress by any other tool in the pipeline. Remember that one cannot read compressed FASTQ files in parallel and our experience shows that in many cases simply decompressing the reads become a significant bottleneck as this process is inherently CPU bound and single threaded.

Yup, I am aware of this. But this has a massive overhead on the size of the outputs produced by any given pipeline, the size of the `work/` directory and generally makes things unusable for users trying to run these pipelines on laptops...this is one of the main reasons we insist on compression where possible.

> And again, my point is that it's up to pipeline to decide what to do with the input / output data and module should not enforce anything here, it's completely against the whole philosophy of modular structures.

This is a reasonable argument but as I mentioned nf-core is about enforcing standards for good practice (see [guidelines](https://github.com/nf-core/modules#general)) and to ensure that the pipelines are usable by as many people as possible. If this means being more efficient with storage then so be it. There will always be exceptions...

> We will need to maintain a fork of FastQC module due to such limitation. And probably some other modules as well due to this.

You can just have locally installed modules in these instances? That is what I am doing. These are modules that need some level of customisation e..g. [here](https://github.com/nf-core/viralrecon/blob/dev/modules/local/cutadapt.nf)

**Comment by asl** [comment]
> this is one of the main reasons we insist on compression where possible.

Sure. It's fine for module to compress the output when necessary. But the limiting the functionality of the tool via module does not make much sense to me.

> You can just have locally installed modules in these instances? That is what I am doing.
 
Right. But the necessity for customization of such trivial module as FastQC looks extremely odd to me. Never mind.
