### ISSUE TITLE
new module: last

### ISSUE THREAD

**Issue by charles-plessy** [nf-core/modules#464]
Hello,

we would like to submit modules related to the [LAST](https://gitlab.com/mcfrith/last) aligner, which we use for pairwise genome alignment and also mapping of Nanopore reads on genomes.  At the moment we are preparing 7 subtools.  Each of these subtools runs one command that is provided by the `last` package on _Bioconda_, and output their results in a single channel. (Of course the modules also have the channel for version numbers.)

 - [x]  `last/lastdb` for creating a _LAST_ index. (command `lastdb`)
 - [x] `last/train` for training parameters. (command `last-train`)
 - [x] `last/lastal` for the alignment itself. (command `lastal`)
 - [x] `last/split` for selecting optimal one-to-one alignments. (command `last-split`)
 - [x] `last/mafswap` for reversing query and target in the alignment. (command `maf-swap`)
 - [x] `last/mafconvert` for converting the alignment files to various formats such as GFF3. (command `maf-convert`)
 - [x] `last/dotplot` for plotting pairwise alignments. (command `last-dotplot`)

Most subtools have a single input, but the most complex one `last/lastal`, has three input channels: one for the indexed sequences, one for an optional (dummy if needed) file for trained parameters, and one for the sequences to align.

To keep things simple when combining the modules, we decided that all input channels are tuples with `val(meta)` and `path(some input files)`. Sometimes, the `meta` information is just ignored. Please let us know if this is a problem.

The core way to use the modules is: (in pseudo-code)

```
lastdb(target sequences)
train(lastdb.out, query sequences)
lastal(lastdb.out, train.out, query sequences)
```

This pattern allows the user to align genomes to genomes, reads to genomes and even genomes to protein databases.

Because in order to test some of the modules we need to produce their input with other modules, I plan to prepare a single pull request at once. Please let me know if this is a problem.

_edit: turned list into checklist_

**Comment by drpatelh** [comment]
Sounds awesome @charles-plessy 😍 Please can you submit them as separate module PRs to nf-core/modules because it makes it much easier to review.

Do you think we could upload some of the test data to [nf-core/test-datasets](https://github.com/nf-core/test-datasets/tree/modules) so we don't have to chain the modules? Be nice if the test data is likely to be re-used for other things.

I think these sorts of conversations are quite easily resolved via a quick chat so if in doubt please join the #modules channel on the [nf-core Slack workspace](https://nf-co.re/join).

**Comment by charles-plessy** [comment]
After the PRs of all the submodules are accepted, we will still need to:

 - [ ] Update LAST to the latest version in bioconda.
 - [ ] Harmonise the `functions.nf` files so that they are the same in all modules.
 - [ ] Correct the detection of index names by searching for `.des` files instead of `.prj` (which can be non-unique).
 - [ ] Harmonise the handling of gzipped MAF files (some tools transparently accept both compressed and non-compressed)
