### ISSUE TITLE
[FEATURE] Deepvariant version 1.6.0 upgrade 

### ISSUE THREAD

**Issue by youpze** [nf-core/modules#4849]
I'm writing a custom Nextflow pipeline, and for variant calling, I'm utilizing the 'docker://google/deepvariant:latest' container, which is version 1.6.0. However, I encountered an issue while running the deepvariant module from NF-core, which aligns with the error reported here: (https://github.com/google/deepvariant/issues/742)

The problem was resolved by removing the line `--intermediate_results_dir=.` , just as the issue reported.  Notably, when I used deepvariant version v1.5.0, everything worked smoothly. I'm curious if others have experienced a similar issue and if there's a potential solution or if this information could be incorporated into the NF-core Nextflow module. 
```[tasklist]
### Tasks
```

**Comment by fellen31** [comment]
I'm closing this issue as it was resolved in https://github.com/nf-core/modules/pull/5801, with `--intermediate_results_dir=.` being changed to `--intermediate_results_dir=tmp`.
