### ISSUE TITLE
Dockerfile or container image provenance information missing from deepvariant module

### ISSUE THREAD

**Issue by mahesh-panchal** [nf-core/modules#4934]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

https://github.com/nf-core/modules/blob/master/modules/nf-core/deepvariant/main.nf points to a container located at
```
container "nf-core/deepvariant:1.5.0"
```
However, unlike Cellranger, there is no Dockerfile in the same directory, or information where the image comes from. 

Slack discussion here: https://nfcore.slack.com/archives/CJRH30T6V/p1708079375154689 between me and @maxulysse .

**Comment by maxulysse** [comment]
note, add info for the gatk containers from the broad too
