### ISSUE TITLE
new module: custom/awk_fai_to_bed

### ISSUE THREAD

**Issue by maxulysse** [nf-core/modules#5132]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by asp8200** [comment]
@maxulysse : Maybe I can do this one? It seems the main thing is to write some nf-test tests for the "new" module, right?

**Comment by asp8200** [comment]
@maxulysse : Concerning the proposed name of the new module - the nf-core tool doesn't like underscores in the name of modules. How about we go with `custom/faitobed`?

**Comment by asp8200** [comment]
Made this [draft](https://github.com/nf-core/modules/pull/5140), but couldn't the nf-core module [gawk](https://github.com/nf-core/modules/tree/master/modules/nf-core/gawk) be used instead?

**Comment by asp8200** [comment]
@maxulysse : How about I make a PR to Sarek where I replace `local/buid_intervals` with `nf-core/gawk`?

**Comment by maxulysse** [comment]
Yeah, let's see if you can make it work

**Comment by asp8200** [comment]
@maxulysse @tdanhorn @ramprasadn : What do you think about [this](https://github.com/nf-core/sarek/pull/1439)?

**Comment by maxulysse** [comment]
> @maxulysse @tdanhorn @ramprasadn : What do you think about [this](https://github.com/nf-core/sarek/pull/1439)?

PURE GENIUS
