### ISSUE TITLE
Update module: propr and propd to produce an optional output for GSEA/GREA

### ISSUE THREAD

**Issue by suzannejin** [nf-core/modules#5142]
Optionally, when one wants to do GSEA or GREA aferwards, produce the output needed for it.
So an adjacency matrix for GREA,
and a gene list for GSEA.

**Comment by BirkirRey** [comment]
Hi Suzanne,

Could you provide some more information on GREA?
What kind of analysis is it?
What kind of adjacency matrix is required?

Best regards,
Birkir

**Comment by suzannejin** [comment]
Hey @BirkirRey! So sorry, I did not see your comment. I will check your pull request tomorrow morning
Cheers
