### ISSUE TITLE
[FEATURE] Port openms/peakpickerhires from pytest to nf-test

### ISSUE THREAD

**Issue by jonasscheid** [nf-core/modules#5156]
### Is your feature request related to a problem? Please describe

[How to migrate from pytest to nf-test](https://nf-co.re/docs/contributing/modules#migrating-from-pytest-to-nf-test)

**Comment by jonasscheid** [comment]
@vagkaratzas thanks for picking this up! 🚀 can you give me the PR reference to this issue?

**Comment by vagkaratzas** [comment]
Here you go: https://github.com/nf-core/modules/pull/5226

**Comment by jonasscheid** [comment]
Awesome! Then we can close this one. Thanks!
