### ISSUE TITLE
Update cellranger/multi output directives to match work in nf-core scrnaseq

### ISSUE THREAD

**Issue by fmalmeida** [nf-core/modules#5236]
### Is your feature request related to a problem? Please describe

This work refers to https://github.com/nf-core/scrnaseq/pull/276
The pipeline now has a custom empty drops filter module and requires that the aligners modules properly have output channel directives for raw/filtered results.

**Comment by fmalmeida** [comment]
Found a way of doing without it. Closing it.

**Comment by vd4mmind** [comment]
Hi @fmalmeida ,

Can you guide me how to run the cellrangermutli? Is this already now supported in launch version 2.5.1? We are interested in the immune profiling that has GEX, HTO, VDJ, etc which will need to run the cellranger multi. I see there is a module but unable to trace if its already available in 2.5.1. Any insights will be appreciated. If it is not, do we know when can we expect in a prod version? Or which dev it is available? Thanks for the wonderful workflows.

**Comment by fmalmeida** [comment]
Hey @vd4mmind ,
Currently there is no automated way of running it. We are currently working in adding a cellranger multi subworkflow to `scrnaseq` however, we have no real idea of when we will be able to have it merged in prod as I can mainly work in it a few hours a week.

So, right now, no real deadline, or real plan. But, if you want, you can track the progress of the work in this PR: https://github.com/nf-core/scrnaseq/pull/276 . Also, if you would have time or would be willing to contribute either with code or feedback, please feel invite to do it.

😄
