### ISSUE TITLE
new module: humann3

### ISSUE THREAD

**Issue by kaurravneet4123** [nf-core/modules#528]
I think it would be good to have a module for [humann3](https://anaconda.org/biobakery/humann)

- [ ] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [ ] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [ ] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to work on the module

**Comment by ramprasadn** [comment]
Hi there!

We’ve noticed there hasn’t been much activity here. Are you still planning on working on this?
If not, you can ignore this message and we’ll close your PR/issue in about 2 weeks

Cheers
the nf-core maintainers
