### ISSUE TITLE
tiddit/sv is missing --threads flag

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/modules#5301]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

The tool Tiddit Sv should have the `--threads {task.cpus}` added: https://github.com/SciLifeLab/TIDDIT/ 

cc https://github.com/nf-core/sarek/issues/1441

**Comment by famosab** [comment]
Closed with #5371
