### ISSUE TITLE
new module: seurat/createSeuratObject

### ISSUE THREAD

**Issue by gesavoigt** [nf-core/modules#5309]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by famosab** [comment]
@gesavoigt Do you have a PR you could link?

**Comment by gesavoigt** [comment]
Hi @famosab, I was planning to implement this but plans have changed, so I am not working on this anymore
