### ISSUE TITLE
new module: GROOT

### ISSUE THREAD

**Issue by SumeetTiwari07** [nf-core/modules#5312]
Using shot-gun reads, [GROOT](https://github.com/will-rowe/groot) is a tool to detect Antibiotic Resistance Genes (ARGs) in metagenomic samples (a.k.a. Resistome Profiling).

```[tasklist]
### Tasks
```

**Comment by SumeetTiwari07** [comment]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by famosab** [comment]
@SumeetTiwari07 Do you still plan to work on this?

**Comment by SumeetTiwari07** [comment]
Nope. I do not have time.
