### ISSUE TITLE
new module: LOFREQ/CALLPARALLEL

### ISSUE THREAD

**Issue by kaurravneet4123** [nf-core/modules#538]
I think it would be good to have a module for [LOFREQ/CALLPARALLEL](https://anaconda.org/bioconda/lofreq)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [ ] I'm working on the module

**Comment by bjohnnyd** [comment]
Hi @kaurravneet4123 , what a coincidence it really is a small world.  I actually need this module and was thinking of adding it and saw this issue. I was wondering if you maybe have a PR ready locally that you did not push yet or are working on it?

**Comment by kaurravneet4123** [comment]
Hi @bjohnnyd, the module is nearly ready. I am going to first finalise the lowfreq/indelqual as I have already made its PR. Just need to work on the feedback. Hopefully, by next week, I would be able to push the lofreq/callparallel as well with a PR. I hope this is ok.
