### ISSUE TITLE
new module: delly

### ISSUE THREAD

**Issue by projectoriented** [nf-core/modules#554]
I think it would be good to have a module for [delly](https://bioconda.github.io/recipes/delly/README.html)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by projectoriented** [comment]
@ewels Hej Phil! How do I go about assigning this module to myself?

**Comment by ewels** [comment]
@projectoriented - should be able to do it with a cog in the top right, Assignees. I just assigned you:

![image](https://user-images.githubusercontent.com/465550/124452881-19511600-dd87-11eb-823d-49c1d87f38e5.png)

Looks like you were not a member of the nf-core GitHub org, so I guess you didn't have the cog. I've just sent you an invite ✉️
