### ISSUE TITLE
new module: tantan

### ISSUE THREAD

**Issue by charles-plessy** [nf-core/modules#560]
I have prepared a _nf-core_-compatible module for the `tantan` software; would you like a pull request for it ?

`tantan` takes biological sequences in FASTA format as input and detects low-complexity and tandem repeat sequences in them.

Upstream repository: <https://gitlab.com/mcfrith/tantan>; primary publication: <https://doi.org/10.1093/nar/gkq1212>

`tantan` has 5 different types of output:

 * `-f0` for masked sequences (FASTA format)
 * `-f1` for repeat probabilities (text format)
 * `-f2` for repeat counts (text format)
 * `-f3` for repeat coordinates (BED format)
 * `-f4` for tandem repeats (text format)

This module requires that its input sequence is not compressed.

By default, the module will output masked sequences in its `fasta` output channel.  It also has a `BED` and a `txt` output channel for the other formats.  The formats and channel are chosen by parsing the command-line arguments for the `-f` option.  For this reason, the use of a space between `-f` and the output type is not accepted and the module will exit with error if it happens.

You can find the module at https://github.com/luslab/modules/commit/30c27ee21e68d79c7fe17ac32fcb1fd84f644e2b if you would like to have a look.

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by louperelo** [comment]
Hi there!

We’ve noticed there hasn’t been much activity here. Are you still planning on working on this? Should we add it to the hackathon 2023 board?
If not, you can ignore this message and we’ll close your PR/Issue in about 2 weeks

Cheers
the nf-core maintainers

**Comment by charles-plessy** [comment]
Thanks for the reminder; we may touch it in an internal hackathon in April, so you can leave the PR open.

**Comment by charles-plessy** [comment]
Superseded by #6256
