### ISSUE TITLE
new module: alevinQC

### ISSUE THREAD

**Issue by KevinMenden** [nf-core/modules#566]
I think it would be good to have a module for [alevinqc](https://bioconda.github.io/recipes/bioconductor-alevinqc/README.html)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by drpatelh** [comment]
See https://github.com/nf-core/modules/pull/418
