### ISSUE TITLE
new module: deeptrio

### ISSUE THREAD

**Issue by abhi18av** [nf-core/modules#568]
I think it would be good to have a module for [DeepTrio](https://github.com/google/deepvariant/blob/r1.1/docs/deeptrio-details.md)

**Comment by ramprasadn** [comment]
Hi there!

We’ve noticed there hasn’t been much activity here. Are you still planning on working on this?
If not, you can ignore this message and we’ll close your PR/issue in about 2 weeks

Cheers
the nf-core maintainers
