### ISSUE TITLE
new module: BUSCO

### ISSUE THREAD

**Issue by charles-plessy** [nf-core/modules#569]
Hello, would there be interest for a [BUSCO](https://busco.ezlab.org/) module ?  I will prepare one privately in any case, and would be pleased to contribute it here.

Test data would need to be submitted to nf-core/test-datasets. I have a branch ready in a fork (https://github.com/oist/plessy_nf-core_test-datasets/commit/7eeb3bb37369e3f74ab9f9f09a8da362e4699105).

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by mahesh-panchal** [comment]
Hi @charles-plessy . I would be interested in such a module. Have you begun work on it?

**Comment by charles-plessy** [comment]
I have an early draft here: https://github.com/luslab/modules/blob/busco/software/busco/main.nf
