### ISSUE TITLE
--soloCBwhitelist option not working

### ISSUE THREAD

**Issue by ulyssebaruchel** [nf-core/modules#5863]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

The way --soloCBwhitelist takes an argument does not seem to work because it is written as metadata but the barcode whitelist needs to be in a (value) channel so it can be loaded into the Docker or Singularity container, and a file cannot be part of metadata. Can you fix it, please? Thank you. (I also think that having the solo as either part of the metadata or as a separate value channel in the input would be preferable.)

**Comment by SPPearce** [comment]
What module is this an issue for?

**Comment by ulyssebaruchel** [comment]
My bad, this is for the Starsolo module (star/starsolo)

**Comment by matq007** [comment]
Can be also closed now? @SPPearce

**Comment by matq007** [comment]
Solved in #6062
