### ISSUE TITLE
Update the bwa/mem tests with the nft-bam plugin

### ISSUE THREAD

**Issue by edmundmiller** [nf-core/modules#5936]
I think we need to update the bwa/mem tests with the nft-bam plugin

_Originally posted by @maxulysse in https://github.com/nf-core/modules/pull/4895#discussion_r1668999909_

**Comment by nvnieuwk** [comment]
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExYmVrZGl6eXBxbnVhbzhudXdldGJidDQydjh4aGd1YzZyM3MxemJvaCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/yBwgX64KAPrHW2ltZ2/giphy.gif)
