### ISSUE TITLE
new module: custom/gfatofasta

### ISSUE THREAD

**Issue by sidorov-si** [nf-core/modules#607]
The `hifiasm` genome assembler, already implemented as a module in nf-core, produces contigs only in the GFA format. But most of the time a user would need a FASTA file as output. I'd like to implement a very simple way of GFA-to-FASTA conversion that is recommended in the [hifiasm README](https://github.com/chhylp123/hifiasm): `awk '/^S/{print ">"$2;print $3}' contigs.gfa > contigs.fa`. I wouldn't like to incorporate the conversion in the `hifiasm` module because `hifiasm` produces several output GFA files and users may want to convert different particular files.

**Comment by heuermh** [comment]
Note this was implemented in https://github.com/nf-core/modules/pull/631 via `dsh-bio` as discussed on nf-core Slack
