### ISSUE TITLE
nf-test (modules/nf-core/fastqscreen/fastqscreen, conda) is broken

### ISSUE THREAD

**Issue by GallVp** [nf-core/modules#6075]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

nf-test 0.8.4
https://code.askimed.com/nf-test
(c) 2021 - 2024 Lukas Forer and Sebastian Schoenherr

Load .nf-test/plugins/nft-bam/0.3.0/nft-bam-0.3.0.jar

Test Process FASTQSCREEN_FASTQSCREEN

  Test [cfce08e5] 'sarscov2 - human' 
    > N E X T F L O W  ~  version 24.04.3
    > Launching `/home/ubuntu/tests/cfce08e57f11ff531d3a4816db63f759/meta/mock.nf` [tiny_lovelace] DSL2 - revision: 471c04fb4a
    > Creating env using conda: /opt/actions-runner/_work/modules/modules/modules/nf-core/fastqscreen/fastqscreen/tests/../../../bowtie2/build/environment.yml [cache /home/ubuntu/tests/cfce08e57f11ff531d3a4816db63f759/work/conda/bowtie2_build-0bdb33689db4de8ae8ba44a99e292048]
    > Staging foreign file: https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/genome/chr21/sequence/genome.fasta
    > [7b/cbb9b0] Submitted process > BOWTIE2_BUILD (genome.fasta)
    > [a4/708cd1] Submitted process > BOWTIE2_BUILD (genome.fasta)
    > Creating env using conda: /opt/actions-runner/_work/modules/modules/modules/nf-core/fastqscreen/fastqscreen/tests/../../../fastqscreen/buildfromindex/environment.yml [cache /home/ubuntu/tests/cfce08e57f11ff531d3a4816db63f759/work/conda/fastqscreen_buildfromindex-83fa9a87c787ec99746ea1f1985adca1]
    > [b8/29c58c] Submitted process > FASTQSCREEN_BUILDFROMINDEX
    > Creating env using conda: /opt/actions-runner/_work/modules/modules/modules/nf-core/fastqscreen/fastqscreen/tests/../environment.yml [cache /home/ubuntu/tests/cfce08e57f11ff531d3a4816db63f759/work/conda/fastqscreen_fastqscreen-e436f3038c0bcf04541ea7de9bbbd7eb]
    > [52/ec2851] Submitted process > FASTQSCREEN_FASTQSCREEN (test)
    > ERROR ~ Error executing process > 'FASTQSCREEN_FASTQSCREEN (test)'
    > 
    > Caused by:
    >   Missing output file(s) `*.png` expected by process `FASTQSCREEN_FASTQSCREEN (test)`
    > 
    > 
    > Command executed:
    > 
    >   fastq_screen --threads 2 \
    >       --aligner bowtie2 \
    >       --conf FastQ_Screen_Genomes/fastq_screen.conf \
    >       test_1.fastq.gz \
    >        \
    >       --outdir .
    >   
    >   cat <<-END_VERSIONS > versions.yml
    >   "FASTQSCREEN_FASTQSCREEN":
    >       fastqscreen: $(echo $(fastq_screen --version 2>&1) | sed 's/^.*FastQ Screen v//; s/ .*$//')
    >   END_VERSIONS
    > 
    > Command exit status:
    >   0
    > 
    > Command output:
    >   (empty)
    > 
    > Command error:
    >   Using fastq_screen v0.15.3
    >   Reading configuration from 'FastQ_Screen_Genomes/fastq_screen.conf'
    >   Adding database sarscov2
    >   Adding database human
    >   Using 2 threads for searches
    >   Option --subset set to 100000 reads
    >   Processing test_1.fastq.gz
    >   Counting sequences in test_1.fastq.gz
    >   Not making subset of 100000 since 100 actual sequences is too low or close enough
    >   Searching test_1.fastq.gz_temp_subset.fastq against sarscov2
    >   Searching test_1.fastq.gz_temp_subset.fastq against human
    >   Perl module GD::Graph::bars not installed, skipping charts
    >   Processing complete
    > 
    > Work dir:
    >   /home/ubuntu/tests/cfce08e57f11ff531d3a4816db63f759/work/52/ec285127ca0c184f8f93d1b7a0a067
    > 
    > Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
    > 
    >  -- Check '/home/ubuntu/tests/cfce08e57f11ff531d3a4816db63f759/meta/nextflow.log' file for details
    > WARN: Got an interrupted exception while taking agent result | java.lang.InterruptedException
Assertion failed: 

assert process.success
       |       |
       |       false
       FASTQSCREEN_FASTQSCREEN

java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
    FAILED (162.994s)

  Assertion failed: 
  
  4 of 5 assertions failed
  
  Nextflow stdout:

### Relevant files

https://github.com/nf-core/modules/actions/runs/10172683953/job/28139842853?pr=6065#logs

**Comment by SPPearce** [comment]
Fixed in #6247

**Comment by GallVp** [comment]
Great!
