### ISSUE TITLE
flye tests fail due to insufficient memory

### ISSUE THREAD

**Issue by GallVp** [nf-core/modules#6165]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

flye tests fail due to insufficient memory

**Comment by famosab** [comment]
This was fixed by removing the tests that had `--raw` in the flag. https://github.com/nf-core/modules/pull/6613

**Comment by GallVp** [comment]
> This was fixed by removing the tests that had `--raw` in the flag. #6613

Great! Thank you!
