### ISSUE TITLE
new module: FusionCatcher

### ISSUE THREAD

**Issue by praveenraj2018** [nf-core/modules#648]
I think it would be good to have a module FusionCatcher for fusion detection in RNAseq data 
(https://github.com/ndaniel/fusioncatcher)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by ramprasadn** [comment]
Hi there!

We’ve noticed there hasn’t been much activity here. Are you still planning on working on this?
If not, you can ignore this message and we’ll close your PR/issue in about 2 weeks

Cheers
the nf-core maintainers
