### ISSUE TITLE
Cron job to run pytest-workflow all

### ISSUE THREAD

**Issue by Emiller88** [nf-core/modules#664]
Maybe once a week or month we should run pytest with all the tags and just see if anything's failing due to whatever changing underneath.

**Comment by grst** [comment]
Only running tests for letters A-F took >13h to finish on github actions: https://github.com/nf-core/modules/actions/runs/1269860702

I don't think we can afford to run this on GH actions - it would block the CI for days. But maybe we could use AWS budget for this? I created a NF workflow to run the tests, we could fire off something similar: 
https://github.com/grst/nf-core-test-modules

**Comment by louperelo** [comment]
Hi there!

We’ve noticed there hasn’t been much activity here. Is this discussion still active?
If not, you can ignore this message and we’ll close your PR/Issue in about 2 weeks

Cheers
the nf-core maintainers

**Comment by grst** [comment]
Not sure if this is still relevant, but [cirun](https://cirun.io/auth/login) can set-up AWS instances on-demand. We tested this for [GPU runners for scverse](https://github.com/scverse/test-gpu-ci) and it works quite well.
