### ISSUE TITLE
Caused by: java.nio.channels.OverlappingFileLockException

### ISSUE THREAD

**Issue by edmundmiller** [nf-core/modules#6664]
When tests are run in CI or locally using conda the tests fail with:

```
  Caused by:
    java.nio.channels.OverlappingFileLockException
```

Caused by: https://github.com/nf-core/modules/pull/6600

## Previous issues
- https://github.com/nf-core/modules/pull/5802#issuecomment-2333658568
- https://nextflow.slack.com/archives/C0477AS31T5/p1718212230419419

**Comment by edmundmiller** [comment]
# Options I see

- Switch CI to micromamba
- Nextflow work around for the conda bug
- #6286 might work for some reason?

**Comment by edmundmiller** [comment]
Alright confirmed that https://github.com/nf-core/modules/actions/runs/10926649144 doesn't seem to fail from an initial test standpoint, AND it's forward progress so it has my vote.

**Comment by maxulysse** [comment]
Sounds perfect to me

**Comment by SPPearce** [comment]
Yep, lets give it a go, we wanted to move to that anyway.

**Comment by apeltzer** [comment]
Any news on this fella? ;-) #6662 sits there and waiting :-P

**Comment by SPPearce** [comment]
Yep, I think we give this a go and revert if everything breaks.

**Comment by maxulysse** [comment]
https://github.com/nf-core/modules/pull/6685

**Comment by maxulysse** [comment]
https://github.com/nf-core/modules/pull/6798

**Comment by edmundmiller** [comment]
Why did this not break when we wrote everything in the conda line before environment ymls?

**Comment by ewels** [comment]
Now hoping that we can fix this in Nextflow: https://github.com/nextflow-io/nextflow/issues/5485

**Comment by ewels** [comment]
Fixed in https://github.com/nextflow-io/nextflow/pull/5489 - any additional testing by folks very welcome!

**Comment by edmundmiller** [comment]
https://nfcore.slack.com/archives/CE6P95170/p1731943264640149

Nextflow v24.10.1 [just released](https://github.com/nextflow-io/nextflow/releases/tag/v24.10.1)!

> Basically this issue had been there when Nextflow tried to make concurrent conda / mamba environments for some time, but only (a) when using an environment.yml file that (b) had no name attribute. As such, it was rarely / if ever seen. Until we recently removed all name attributes from all nf-core [#modules](https://nfcore.slack.com/archives/CJRH30T6V) 🙄 
Updating Nextflow to this patch release should solve this issue if you had hit it.
@ewels 

Closing this but leaving it pinned in case anyones runs into this error

**Comment by maxulysse** [comment]
I would have kept it open until we push up the minimal NXF version with a tools release
