### ISSUE TITLE
update module: cellranger/mkfastq

### ISSUE THREAD

**Issue by nschcolnicov** [nf-core/modules#6699]
Cellranger/mkfastq stub run runs unnecesary processes such as gzip and creates non-empty files

FYI @edmundmiller

**Comment by nschcolnicov** [comment]
I created a PR to try to have the stub run as minimal as possible. https://github.com/nf-core/modules/pull/6700

I couldn't remove the gzip command part because nf-test complains about it. I think it has to do with nf-test trying to read the gzip output file using a gzip reader, while it is in reality an empty .txt file. This is the error that I got when trying to do something like "touch fastq.gz" and then run nf-test.
[error.txt](https://github.com/user-attachments/files/17154473/error.txt)

**Comment by edmundmiller** [comment]
Ah that makes more sense!
