### ISSUE TITLE
new module: alphafold

### ISSUE THREAD

**Issue by abhi18av** [nf-core/modules#673]
I think alphafold would make for a good module given the rise of usage of ML oriented tools in Bioinformatics.

https://github.com/deepmind/alphafold

As of now, only a docker container exists from Google.

**Comment by ramprasadn** [comment]
Hi there!

We’ve noticed there hasn’t been much activity here. Are you still planning on working on this?
If not, you can ignore this message and we’ll close your PR/issue in about 2 weeks

Cheers
the nf-core maintainers
