### ISSUE TITLE
new module: Hiphase

### ISSUE THREAD

**Issue by tanyasarkjain** [nf-core/modules#6856]
### Is there an existing module for this?

- [x] I have searched for the existing module

### Is there an open PR for this?

- [x] I have searched for existing PRs

### Is there an open issue for this?

- [x] I have searched for existing issues

### Further Information

https://github.com/PacificBiosciences/HiPhase

### Are you going to work on this?

- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by fellen31** [comment]
Closed with https://github.com/nf-core/modules/pull/6854 I believe.
