### ISSUE TITLE
new module: MAFFT/GUIDETREE

### ISSUE THREAD

**Issue by luisas** [nf-core/modules#7096]
### Is there an existing module for this?

- [x] I have searched for the existing module

### Is there an open PR for this?

- [x] I have searched for existing PRs

### Is there an open issue for this?

- [x] I have searched for existing issues

### Are you going to work on this?

- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by luisas** [comment]
Hey @MillironX @Joon-Klaps , I would like to add a mode of MAFFT to generate only a guide tree (https://mafft.cbrc.jp/alignment/software/treeout.html). 

To do this, I will have to move MAFFT to MAFFT/ALIGN. What do you think?

**Comment by luisas** [comment]
This is currently my PR 
https://github.com/nf-core/modules/pull/7097

**Comment by Joon-Klaps** [comment]
Is there a need to create a new module for this over just adding an optional output to the current module?

**Comment by Joon-Klaps** [comment]
Nope, no strong feelings here 😄. If other modules have done something similar, I'm all for consistency across tools so go for it! Ping me when you need a review.

**Comment by luisas** [comment]
Hey @Joon-Klaps, great! :) 

The PR is ready, I got a review already but because they had to check the code because there were some errors with the linter. 
So I do not need the review, thanks a ton anyways!
