### ISSUE TITLE
new module: sentieon/bwamem

### ISSUE THREAD

**Issue by Gwennid** [nf-core/modules#732]
I think it would be good to have a module for sentieon (https://bioconda.github.io/recipes/sentieon/README.html) bwa mem (mapping).

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by Gwennid** [comment]
Exists as a local module in nf-core/raredisease (https://github.com/nf-core/raredisease/tree/dev/modules/local/sentieon)

**Comment by Emiller88** [comment]
https://github.com/seqeralabs/nf-sentieon/blob/717e3b4395eb6076715a1cff089c0f82e4b1d449/workflows/sentieon.nf#L42

**Comment by asp8200** [comment]
Is anybody actively working on this at the moment?

**Comment by Gwennid** [comment]
Not that I know of. I can close the issue (as long as the raredisease pipeline is concerned, we are happy with local modules).

**Comment by asp8200** [comment]
> Not that I know of. I can close the issue (as long as the raredisease pipeline is concerned, we are happy with local modules).

We want to implement Sentieon in Sarek, and I think the way to go about that is to first implement nf-modules for the different Sentieon tools.  So I think we should keep these issues open in the modules-repo.
