### ISSUE TITLE
new module: sentieon/dedup

### ISSUE THREAD

**Issue by Gwennid** [nf-core/modules#734]
I think it would be good to have a module for Sentieon (https://bioconda.github.io/recipes/sentieon/README.html) Dedup (second step in marking duplicates).

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by Emiller88** [comment]
https://github.com/seqeralabs/nf-sentieon/blob/717e3b4395eb6076715a1cff089c0f82e4b1d449/workflows/sentieon.nf#L44

**Comment by asp8200** [comment]
done
