### ISSUE TITLE
Fix `versions.yml` in all modules

### ISSUE THREAD

**Issue by grst** [nf-core/modules#745]
## COMPLETED

- [x] 	abacas (assigned @drpatelh)
- [x] 	agrvate (assigned @drpatelh)
- [x] 	bandage/image (assigned @drpatelh)
- [x] 	bismark/align (assigned @drpatelh)
- [x] 	bismark/deduplicate (assigned @drpatelh)
- [x] 	bismark/genomepreparation (assigned @drpatelh)
- [x] 	bismark/methylationextractor (assigned @drpatelh)
- [x] 	bismark/report (assigned @drpatelh)
- [x] 	bismark/summary (assigned @drpatelh)
- [x] 	bowtie/align (assigned @drpatelh)
- [x] 	bowtie/build (assigned @drpatelh)
- [x] 	bowtie2/align (assigned @drpatelh)
- [x] 	bowtie2/build (assigned @drpatelh)
- [x] 	bwa/aln (assigned @drpatelh)
- [x] 	bwa/index (assigned @drpatelh)
- [x] 	bwa/mem (assigned @drpatelh)
- [x] 	bwa/sampe (assigned @drpatelh)
- [x] 	bwa/samse (assigned @drpatelh)
- [x] 	bwamem2/index (assigned @drpatelh)
- [x] 	bwamem2/mem (assigned @drpatelh)
- [x] 	bwameth/align (assigned @drpatelh)
- [x] 	bwameth/index (assigned @drpatelh)
- [x] 	cat/fastq (assigned @drpatelh)
- [x] 	chromap/chromap  (assigned @rpetit3)
- [x] 	delly/call  (assigned @rpetit3)
- [x] 	ensemblvep  (assigned @rpetit3)
- [x] 	expansionhunter  (assigned @rpetit3)
- [x] 	fgbio/callmolecularconsensusreads  (assigned @rpetit3)
- [x] 	fgbio/sortbam  (assigned @rpetit3)
- [x] 	flash (assigned @drpatelh)
- [x] 	gatk4/applybqsr (assigned @drpatelh)
- [x] 	gatk4/baserecalibrator (assigned @drpatelh)
- [x] 	gatk4/bedtointervallist (assigned @drpatelh)
- [x] 	gatk4/createsequencedictionary (assigned @drpatelh)
- [x] 	gatk4/fastqtosam (assigned @drpatelh)
- [x] 	gatk4/getpileupsummaries (assigned @drpatelh)
- [x] 	gatk4/haplotypecaller (assigned @drpatelh)
- [x] 	gatk4/intervallisttools (assigned @drpatelh)
- [x] 	gatk4/markduplicates (assigned @drpatelh)
- [x] 	gatk4/mergebamalignment (assigned @drpatelh)
- [x] 	gatk4/mergevcfs (assigned @drpatelh)
- [x] 	gatk4/mutect2 (assigned @drpatelh)
- [x] 	gatk4/revertsam (assigned @drpatelh) 
- [x] 	gatk4/samtofastq (assigned @drpatelh)
- [x] 	gatk4/splitncigarreads (assigned @drpatelh)
- [x] 	gatk4/variantfiltration (assigned @drpatelh)
- [x] 	genmap/index (assigned @drpatelh)
- [x] 	glnexus (assigned @rpetit3)
- [x] 	graphmap2/align (assigned @drpatelh)
- [x] 	graphmap2/index (assigned @drpatelh)
- [x] 	gunzip (assigned @drpatelh)
- [x] 	hifiasm (assigned @rpetit3)
- [x] 	iqtree (assigned @jfy133)
- [x] 	ivar/consensus (assigned @drpatelh)
- [x] 	ivar/trim (assigned @drpatelh)
- [x] 	ivar/variants (assigned @drpatelh)
- [x] 	kallisto/index (assigned @JoseEspinosa)
- [x] 	kallistobustools/count (assigned @JoseEspinosa)
- [x] 	kallistobustools/ref (assigned @JoseEspinosa)
- [x] 	kleborate (assigned @rpetit3)
- [x] 	kraken2/kraken2 (assigned @drpatelh)
- [x] 	lofreq/call (assigned @drpatelh)
- [x] 	lofreq/callparallel (assigned @drpatelh)
- [x] 	lofreq/filter (assigned @drpatelh) 
- [x] 	lofreq/indelqual (assigned @drpatelh)
- [x] 	methyldackel/extract (assigned @drpatelh)
- [x] 	methyldackel/mbias (assigned @drpatelh)
- [x] 	minia (assigned @rpetit3)
- [x] 	nanoplot (assigned @JoseEspinosa)
- [x] 	optitype  (assigned @JoseEspinosa, issue opened #783)
- [x] 	pairix (assigned @JoseEspinosa)
- [x] 	pbccs (assigned @JoseEspinosa)
- [x] 	picard/markduplicates (assigned @jfy133)
- [x] 	picard/mergesamfiles(assigned @jfy133)
- [x] 	plasmidid (assigned @JoseEspinosa)
- [x] 	plink/vcf (assigned @jfy133)
- [x] 	preseq/lcextrap (assigned @drpatelh)
- [x] 	prokka (assigned @JoseEspinosa)
- [x] 	pydamage/analyze (assigned @jfy133)
- [x] 	pydamage/filter (assigned @jfy133)
- [x] 	qualimap/bamqc (assigned @drpatelh)
- [x] 	raxmlng (assigned @JoseEspinosa)
- [x] 	rsem/preparereference (assigned @drpatelh)
- [x] 	salmon/index (assigned @drpatelh)
- [x] 	samtools/ampliconclip (assigned @drpatelh)
- [x] 	samtools/faidx (assigned @drpatelh)
- [x] 	samtools/fastq (assigned @drpatelh)
- [x] 	samtools/flagstat (assigned @drpatelh)
- [x] 	samtools/idxstats (assigned @drpatelh)
- [x] 	samtools/index (assigned @drpatelh)
- [x] 	samtools/merge (assigned @drpatelh)
- [x] 	samtools/mpileup (assigned @drpatelh)
- [x] 	samtools/sort (assigned @drpatelh)
- [x] 	samtools/stats (assigned @drpatelh)
- [x] 	samtools/view (assigned @drpatelh)
- [x] 	seacr/callpeak (assigned @drpatelh)
- [x] 	seqkit/split2 (assigned @drpatelh)
- [x] 	seqtk/sample (assigned @drpatelh)
- [x] 	seqtk/subseq (assigned @drpatelh)
- [x] 	sequenzautils/bam2seqz (assigned @drpatelh)
- [x] 	sequenzautils/gcwiggle (assigned @drpatelh)
- [x] 	shovill (assigned @JoseEspinosa)
- [x] 	snpeff (assigned @jfy133)
- [x] 	star/genomegenerate (assigned @drpatelh)
- [x] 	stringtie/merge (assigned @drpatelh)
- [x] 	stringtie/stringtie (assigned @drpatelh)
- [x] 	subread/featurecounts (assigned @grst)
- [x] 	tabix/bgzip (assigned @drpatelh)
- [x] 	tabix/bgziptabix (assigned @drpatelh)
- [x] 	tabix/tabix (assigned @drpatelh)
- [x] 	tiddit/sv (assigned @drpatelh)
- [x] 	trimgalore (assigned @drpatelh)
- [x] 	ucsc/bigwigaverageoverbed (assigned @drpatelh)
- [x] 	ucsc/wigtobigwig (assigned @drpatelh)
- [x] 	unicycler (fixed by, or before, #1041)
- [x] 	untar (assigned @drpatelh)
- [x] 	unzip (assigned @drpatelh)
- [x] 	vcftools (assigned @jfy133)
- [x] 	yara/index (assigned @drpatelh)
- [x] 	yara/mapper (assigned @grst: MD5sum mismatch on our HPC, works locally. Both with singularity. How is this even possible??)

**Comment by drpatelh** [comment]
The typical command used to run `pytest` has changed now. Don't forget to add `NF_CORE_MODULES_TEST=1` to the beginning. We need to export that environment variable to be able to test the versions stuff.

## Docker:
```
cd /path/to/git/clone/of/nf-core/modules/
NF_CORE_MODULES_TEST=1 PROFILE=docker pytest --tag fastqc --symlink --keep-workflow-wd
```

## Singularity
```
cd /path/to/git/clone/of/nf-core/modules/
NF_CORE_MODULES_TEST=1 TMPDIR=~ PROFILE=singularity pytest --tag fastqc --symlink --keep-workflow-wd
```

**Comment by grst** [comment]
If anyone gets a `FileNotFoundError` for `versions.yml` like this one, then double-check that the workflow name in `test.yml` needs to start with the tool name.

```
FileNotFoundError: [Errno 2] No such file or directory: '/data/scratch/sturm/projects/2021/nf-core-modules-test-2/18/e188685ed693dac21be7e96d1ac8f3/pytest-workflow/Run_bismark_align_single-end_test_workflow/output/run/versions.yml'
                                   
/data/scratch/sturm/projects/2021/nf-core-modules-test-2/conda/nf-core-tools-dev-5bfdd78995f6a1657f45a07545dfe96b/lib/python3.8/pathlib.py:1078: FileNotFoundError
```

The fix of `test.yml`: 
```diff
-- name: Run bismark align single-end test workflow
+- name: bismark align single-end test workflow
```

**Comment by jfy133** [comment]
Note, updated profile command: 

```console
NF_CORE_MODULES_TEST=1 TMPDIR=/tmp/ PROFILE=singularity pytest tests/modules/fgbio/sortbam --symlink --wt 2 --keep-workflow-wd
```

**Comment by muffato** [comment]
The two tools that were as TODO actually got fixed a few weeks after
