### ISSUE TITLE
new module: gatk4/CombineGVCFs

### ISSUE THREAD

**Issue by noirot** [nf-core/modules#746]
I think it would be good to have a module for [gatk4](https://bioconda.github.io/recipes/gatk4/README.html)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by noirot** [comment]
I absolutely do not have time to code it. If somebody can, go for it

**Comment by maxulysse** [comment]
@GCJMackenzie is this anything of interest for you by any chance?

**Comment by GCJMackenzie** [comment]
@maxulysse  I will most likely have my hands full with finishing up the modules I have open and then making the rest of the subworkflows I have planned, so it would probably be quite some time before I could take a look at this (i.e. very unlikely before the new year). But if no one else has time before then, I would be happy to.

combineGVCFs is more or less a legacy tool now, genomicsdbworkspaces (made with genomicsdbimport) should work with most gatk4 tools in the more recent releases, it may be worth looking into if this is an urgent issue.

**Comment by sateeshperi** [comment]
need this for a workflow.....picking this up

**Comment by sateeshperi** [comment]
closes with #1342
