### ISSUE TITLE
Missing 'params.modules' entry causes error "Cannot get property 'args' on null object"

### ISSUE THREAD

**Issue by chasemc** [nf-core/modules#802]
I wanted to document an error that was pretty difficult to debug in case someone else has the issue. 

If your script imports a module paramter:

`include { PROTEIN_HASH   } from '../modules/local/protein_hash.nf' addParams( options: modules[ 'protein_hash' ])      `

But the module param (`'protein_hash'`) doesn't exist, the following error occurs when running the pipeline:
`Cannot get property 'args' on null object`

A message also says to check the `functions.nf` file, though the problem can just be a missing module param

**Comment by Emiller88** [comment]
I'm going to close this, since we no longer use `addParams` since #814
