### ISSUE TITLE
new module: metabat2

### ISSUE THREAD

**Issue by maxibor** [nf-core/modules#820]
I think it would be good to have a module for [metabat2](https://bioconda.github.io/recipes/metabat2/README.html)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by muffato** [comment]
There are two metabat2 subtools in nf-core: jgisummarizebamcontigdepths and metabat2, cf https://github.com/nf-core/modules/tree/master/modules/nf-core/metabat2
Are any other needed for this issue to be resolved ?

**Comment by d4straub** [comment]
As far as I see it, the issue can be closed.
