### ISSUE TITLE
new module: pilon

### ISSUE THREAD

**Issue by d4straub** [nf-core/modules#831]
I think it would be good to have a module for [pilon](https://bioconda.github.io/recipes/pilon/README.html)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

This could be used to improve nf-core/bacass and is suggested [here](https://github.com/nf-core/bacass/issues/57) and used in nf-core/mag.

**Comment by louperelo** [comment]
Hi there!

We’ve noticed there hasn’t been much activity here. Should this issue be added to the hackathon 2023?
If not, you can ignore this message and we’ll close your PR/Issue in about 2 weeks

Cheers
the nf-core maintainers
