### ISSUE TITLE
new module: circularmapper/circulargenerator

### ISSUE THREAD

**Issue by jfy133** [nf-core/modules#842]
I think it would be good to have a module for [circularmapper](https://bioconda.github.io/recipes/circulargenerator/README.html)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [ ] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by louperelo** [comment]
Hi there!

We’ve noticed there hasn’t been much activity here. Are you still planning on working on this? Should we add it to the hackathon 2023 board?
If not, you can ignore this message and we’ll close your PR/Issue in about 2 weeks.

Cheers
the nf-core maintainers

**Comment by jfy133** [comment]
We still need these, so reopening. I think they were closed because they were in the 'old' style of modules.
