### ISSUE TITLE
Add codeowners

### ISSUE THREAD

**Issue by Emiller88** [nf-core/modules#86]
To get pinged and have actual owners who keep up with the software that the modules are taking advantage of.

**Comment by Emiller88** [comment]
See https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners for docs

**Comment by drpatelh** [comment]
Just catching up with this but is it not something we can get from the `meta.yml` files that are shipped with the module files? I am getting slightly edgy about having to update various files in the repo when adding a module.

**Comment by Emiller88** [comment]
I don't think we can parse files in `meta.yml` or in the `CODEOWNERS` file. I also don't think this has to be updated, just like that a `meta.yml`isn't a requirement. For example if you're just throwing one in from rnaseq. But someone who's making a PR for a module, it might be nice to have them get pinged on any requests for changes to that module.

**Comment by drpatelh** [comment]
Why can't we parse the `meta.yml`? That is the eventual plan. [`meta.yml`](https://github.com/nf-core/modules#documentation) should be a requirement! 😅 

I see every PR on every repo on nf-core all of the time 👀 Save yourself!!

**Comment by Emiller88** [comment]
I meant just parse it with some bash magic in the `CODEOWNERS`wasn't a possibility. But now you've got me dreaming.

We can make a github workflow, that parses all the meta.yaml files, and whenever a change occurs in one of them, it checks for any changes in the owners, and regenerates the CODEOWNERS file if necessary. For a bonus, it might fail if a module doesn't have a `meta` file :stuck_out_tongue:

**Comment by grst** [comment]
That sounds overly complicated... If we parse the meta file anyway, we can also let the "nf core bot" ping the maintainers. That's how it's done in bioconda.

I have to say that I find it quite elegant that CODEOWNERS "natively" notifies people without having us to mess with bots, but I am also wary about having to update too many different places.

**Comment by Emiller88** [comment]
I completely agree it would be over-engineered. But comparatively updating the CODEOWNERS looks easy now. 

I really prefer the "native" notification over something else we have to maintain. I think we might be better off expanding the contributing guidelines, and it might just be something we have to do when someone makes a new PR.

A basic list:
- `main.nf`
- `functions.nf`
- `meta.yml`(With all the documentation)
- `tests/software/main.nf`
- `tests/software/test.yml`
- `.github/workflow/software.yml`
- Add a line to CODEOWNERS

I guess at that point I think adding a single line isn't moving the barrier to entry much higher in my opinion.

**Comment by Emiller88** [comment]
https://github.com/milin/gitown This might keep it up to date magically.

**Comment by jasmezz** [comment]
Hi there!

We’ve noticed there hasn’t been much activity here. Are you still planning on working on this?
If not, you can ignore this message and we’ll close your PR in about 2 weeks.
If you think this is still relevant, you can also add it to the [hackathon2023 project board](https://github.com/orgs/nf-core/projects/41).

Cheers
the nf-core maintainers
