### ISSUE TITLE
[BUG] The update of the human test data suite could impact the listed modules

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/modules#861]
See also:  https://github.com/nf-core/test-datasets/pull/356 for details

TODO:

- [x] update modules config file by adding the cram files

Modules that need recalculated output md5sums possibly:

- [ ] mutect2
- [ ] getpileupsummaries
- [ ] expansionhunter
- [ ] delly
- [ ] string tie/merge
- [x] damageprofiler
- [x] pydamage/analyzer
- [ ] bamtools/split
- [ ] optitype

**Comment by louperelo** [comment]
This problem seems to have been addressed here: damageprofiler PR #612 and pydamage_analyzer PR #863 .
