### ISSUE TITLE
new module: r-sequenza

### ISSUE THREAD

**Issue by priesgo** [nf-core/modules#886]
I think it would be good to have a module for r-sequenza (https://bioconda.github.io/recipes/r-sequenza/README.html)

Together with the other modules sequenzautils/* it could used to implement a subworkflow following the recommended sequenza pipeline as documented here https://cran.r-project.org/web/packages/sequenza/vignettes/sequenza.html

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by louperelo** [comment]
Hi there!

We’ve noticed there hasn’t been much activity here. Are you still planning on working on this?
If not, you can ignore this message and we’ll close your PR/Issue in about 2 weeks or add it to the hackathon board 2023.

Cheers
the nf-core maintainers
