### ISSUE TITLE
PycoQC modules only accepts fast5 summary files

### ISSUE THREAD

**Issue by d4straub** [nf-core/modules#889]
## Is your feature request related to a problem? Please describe

PYCOQC module only accepts fast5 summary files, no raw fast5 files

## Describe the solution you'd like

See in [nf-core/bacass](https://github.com/nf-core/bacass/blob/master/modules/local/pycoqc.nf):

[L33-L37](https://github.com/nf-core/bacass/blob/959967364c7c0105b5b271acf0441fa9290e0d4c/modules/local/pycoqc.nf#L33-L37)

This is also mentioned in nf-core/bacass#61

**Comment by louperelo** [comment]
Hi there!

We’ve noticed there hasn’t been much activity here. Are you still planning on working on this? Should we add it to the hackathon 2023 board?
If not, you can ignore this message and we’ll close your PR/Issue in about 2 weeks.

Cheers
the nf-core maintainers
