### ISSUE TITLE
Nanoplot could also accept .fq.gz as input

### ISSUE THREAD

**Issue by d4straub** [nf-core/modules#891]
## Is your feature request related to a problem? Please describe

The nanoplot module is very restrictive in input files naming, only `.fastq.gz` are allowed but some software produces `.fq.gz` and it would be nice to usually be rather flexible with input I think.

## Describe the solution you'd like

```
    def input_file = ("$ontfile".endsWith(".fastq.gz")) ? "--fastq ${ontfile}" :
        ("$ontfile".endsWith(".txt")) ? "--summary ${ontfile}" : ''
```
use
```
    def input_file = ("$ontfile".endsWith(".fastq.gz")) ? "--fastq ${ontfile}" :
        ("$ontfile".endsWith(".fq.gz")) ? "--fastq ${ontfile}" :
        ("$ontfile".endsWith(".txt")) ? "--summary ${ontfile}" : ''
```

## Additional context

This was also mentioned in https://github.com/nf-core/bacass/issues/61

**Comment by louperelo** [comment]
Hi there!

We’ve noticed there hasn’t been much activity here. Are you still planning on working on this? Should we add it to the hackathon 2023 board?
If not, you can ignore this message and we’ll close your PR/Issue in about 2 weeks.

Cheers
the nf-core maintainers
