### ISSUE TITLE
new module: eggnog-mapper

### ISSUE THREAD

**Issue by emnilsson** [nf-core/modules#905]
I think it would be good to have a module for [eggnog-mapper](https://bioconda.github.io/recipes/eggnog-mapper/README.html?highlight=eggnog#package-package%20&#x27;eggnog-mapper&#x27;).

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by rpetit3** [comment]
Hi @emnilsson, were you still working on this? If not, I'd like to take a crack at it. Cheers!

**Comment by emnilsson** [comment]
Hi @rpetit3, it's sadly just on my to-do-list (got sidetracked), so feel free to work on it! I'll remove my "assignation".

**Comment by ramprasadn** [comment]
Hi there!

We’ve noticed there hasn’t been much activity here. Are you still planning on working on this?
If not, you can ignore this message and we’ll close your PR/issue in about 2 weeks

Cheers
the nf-core maintainers
