### ISSUE TITLE
new module: krakenuniq/krakenuniq

### ISSUE THREAD

**Issue by ilight1542** [nf-core/modules#911]
I think it would be good to have a module for [KrakenUniq](https://github.com/fbreitwieser/krakenuniq)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by ramprasadn** [comment]
Do you think we can close this issue @jfy133 ? It looks like modules have been added already. https://github.com/nf-core/modules/tree/master/modules/nf-core/krakenuniq

**Comment by jfy133** [comment]
Yes we  can!
