### ISSUE TITLE
new module: beagle

### ISSUE THREAD

**Issue by Mxrcon** [nf-core/modules#972]
I think it would be good to have a module for [beagle](https://bioconda.github.io/recipes/beagle/README.html)

- [x] This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- [x] There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- [x] There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- [x] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by muffato** [comment]
@Mxrcon : it seems to have been addressed by https://github.com/nf-core/modules/pull/2723 ?

**Comment by Mxrcon** [comment]
> @Mxrcon : it seems to have been addressed by https://github.com/nf-core/modules/pull/2723 ?

Yes! There are different versions of beagle (3 and 5), but for now the additional of version 5 is enough to close this issue

**Comment by muffato** [comment]
Super, thanks for the quick check !
